### ISSUE TITLE
Security Updated 4.6.6

### ISSUE THREAD

**Issue by ViceIce** [phpmyadmin/docker#105]
A security update is out [there](https://www.phpmyadmin.net/files/4.6.6).

Please provide a update to version 4.6.6.

Regards,
Michael

**Comment by nijel** [comment]
Sorry, I somehow forgot to update the Docker container on release.

**Comment by ViceIce** [comment]
Currently only edge tag is updated. Will you update the lastest tag too?

**Comment by nijel** [comment]
Yes, doing that right now. I was waiting for tests will pass, I didn't want to ship something broken ;-).

**Comment by ViceIce** [comment]
Ok. Now it's there. Thanks.
