### ISSUE TITLE
Support docker secrets

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/docker#108]
more information about docker secrets:
https://docs.docker.com/engine/swarm/secrets/#build-support-for-docker-secrets-into-your-images

**Comment by MetalArend** [comment]
An example implementation can be found in the wordpress container: https://github.com/docker-library/wordpress/blob/master/docker-entrypoint.sh

**Comment by nijel** [comment]
Patches are certainly welcome

**Comment by ivorscott** [comment]
This functionality works now in the official image by appending _FILE to env vars. Why is this still open? We should probably mention this in the Dockerhub repository as well.

**Comment by J0WI** [comment]
This has been fixed.
