### ISSUE TITLE
Environment Variables Is Not Working

### ISSUE THREAD

**Issue by elshafey** [phpmyadmin/docker#114]
The passed Environment Variables is not working well in compose file.

I tried to set PMA_HOST,PMA_USER,PMA_PASSWORD but has no effect, though when I tried to echo these variables from the bash inside the container, it worked well

here the compose snippet

environment:
            - PMA_ARBITRARY=1
            - MYSQL_ROOT_PASSWORD=
            - PMA_HOST=172.16.238.5
            - PMA_USER=root
            - PMA_PASSWORD=

**Comment by nijel** [comment]
What indeed was not working were *empty* variables, this has been fixed in 1bcaeb5fece5f9dd72a9bb2036fdf7d3c7756cd4.
