### ISSUE TITLE
Remove VOLUME dockerfile instruction

### ISSUE THREAD

**Issue by etki** [phpmyadmin/docker#117]
Currently there is VOLUME declared in Dockerfile (`VOLUME /sessions`). VOLUME is commonly mistaken for some magic thing that has relevance to persistence, but in fact it is just a directory outside of standard graph which **is created every time container is started** and **it is never remounted automatically on following container starts** and, finally, **it is never cleaned automatically, so it stays on your filesystem forever because you don't even know where it is or that it exists**. Consider following example:

```Dockerfile
FROM alpine
RUN mkdir /var/volumes-are-harmful && echo "version 1" > /var/volumes-are-harmful/data
WORKDIR /var/volumes-are-harmful
VOLUME /var/volumes-are-harmful
```

```bash
docker build -t volumes-are-harmful .
docker run volumes-are-harmful sh -c 'echo "version 2" > data && touch new-data'
```

If someone expects `data` to have new content and `new-data` to exist on next run - well, it will never happen

```bash
docker run volumes-are-harmful cat data
> version 1
docker run volumes-are-harmful ls
> data
```

Well, let's inspect the damage:

```bash
docker volume ls
DRIVER              VOLUME NAME
local               1099932cae633150fb387ca42e292356f5de5f86a5590522785ad45502ba8119
local               229eab98bb5fab47adf72d4df1447922fb445a7b657a295d0caee71fcd98a567
local               6a4d03ae85edb523c9f1b17b45b3940c3db906fe7d63e86183d78c72777d963f
```

Yes, those are three directories buried somewhere deep in filesystem that will never be used again. Host volumes (not mounts) were bad decision from the very beginning, and some steps were made to evade problems they bring in (specifying `--rm` would destroy volume on exit as well), but by default by using volume you force user to bloat their filesystem on every run - quite the opposite containers were to bring in.

That means it's just filesystem garbage unless user has stated that he wants to mount container directory to host directory - and that doesn't need to mark directory as VOLUME. Even if user needs to share container contents (surely not the case for sessions and, actually, another antipattern), he/she can (again!) declare volume at container start. But there is no inverse action: if VOLUME is specified, you can't cancel it, only mount somewhere in the host system and take all collision and garbage collection burden on yourself. Dockerfile volumes are completely useless and harmful.

Because of that i beg to remove `VOLUME /sessions` from Dockerfile.

**Comment by nijel** [comment]
I've thought that `VOLUME` is necessary for being able to mount host volumes...
