### ISSUE TITLE
export db or table error

### ISSUE THREAD

**Issue by ft20082** [phpmyadmin/docker#119]
This repository contains only Docker integration of phpMyAdmin.

docker export error.

2017/04/17 03:24:10 [error] 26#26: *12975 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot 'break' 2 levels in /www/export.php on line 864" while reading response header from upstream, client: 192.168.1.99, server: _, request: "POST /export.php HTTP/1.0", upstream: "fastcgi://unix:/var/run/php/php-fpm.sock:", host: "task.test.com"

i use phpmyadmin version is 4.0.10.20, and i build myself.

**Comment by ft20082** [comment]
need php lower version, like php5.5.x

**Comment by nijel** [comment]
Indeed phpMyAdmin 4.0.10.20 does not support PHP 7.
