### ISSUE TITLE
Unable to export datasets for large queries/large results.

### ISSUE THREAD

**Issue by chrisburrell** [phpmyadmin/docker#122]
One of the changes recently has meant we can longer 'EXPORT' queries. We get a "token error". There's nothing in the logs that helps diagnose this. Small queries seem to be ok (sometimes), but larger queries are always prevented (not sure if it's the SQL text or if it's the data results that cause the issue).

Rolling back to the latest 4.6.6-2 release seems to fix the issue.

**Comment by nijel** [comment]
This has been fixed for 4.7.1, see phpmyadmin/phpmyadmin#13182.
