### ISSUE TITLE
supervisord CRIT logs & setcap usage instead of root

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/docker#125]
1. after running the container, the content of "/var/log/supervisord.log" is:
CRIT Supervisor running as root (no user in config file)
CRIT Server 'unix_http_server' running without any HTTP authentication checking

more information about first message:
https://stackoverflow.com/questions/19918177/starting-supervisord-as-root-or-not#22048473

the second message can be fixed by adding dummy user & pass options, more information:
https://github.com/Supervisor/supervisor/issues/717#issuecomment-176860145
(Note: the default prems of the used socket /run/supervisord.sock is 0700, thus there is no issue here, still supervisor don't take this into account when choosing to show the message...)

2. currently the image require running under root, more information in previous issue:
https://github.com/phpmyadmin/docker/issues/18#issuecomment-220550024 "Use port 80 instead of port 8080"
it probably possible to use setcap to allow needed capabilities (such as: cap_net_bind_service to bind on port < 1024) instead of root, more information:
https://stackoverflow.com/questions/413807/is-there-a-way-for-non-root-processes-to-bind-to-privileged-ports-on-linux#414258

**Comment by williamdes** [comment]
Since 78e3cb7aba41b233281f81d8b264d95505c43c96 and other commits removed supervisor this issue no longer exists
