### ISSUE TITLE
HAProxy Health Checks failing due to 405 Not Allowed (Nginx) error returned by phpmyadmin/phpmyadmin docker container.

### ISSUE THREAD

**Issue by bs-thomas** [phpmyadmin/docker#126]
Hello there,

I'm running phpmyadmin/phpmyadmin docker container behind an haproxy as follows:

    backend ecs_app_servers_phpmyadmin.beamstyle.com.hk
      balance roundrobin
      option redispatch
      option forwardfor
      option httpchk OPTIONS /
        server i-0cadacf3af0ecc8b3 172.31.31.31:8000 weight 8 maxconn 120 check inter 10s

However, the health checks are not passing, returning me a 503 Service Unavailable.  Obviously, that's not quite helpful.

After a long investigation, I noticed that the problem lies in the command "OPTIONS".  Using Postman, I was able to see the response of sending an "OPTIONS" request to the container returns the following:

405 Not Allowed
nginx

I think this is ultimately the problem causing my health checks to fail.  However, I'm running an automated script in haproxy, with many containers behind.  Change that script to make a "GET" request is not going to work for me.  I would want to somehow make phpmyadmin not return 405 Not Allowed error.  Is there any way to override this behavior?

Any help would be much appreciated.

Thank you very much!

**Comment by nijel** [comment]
Why are you actually using OPTIONS request for this and not HEAD?

See also https://github.com/phpmyadmin/docker/issues/64

**Comment by emanuelb** [comment]
phpmyadmin doesn't expect cross-origin-ajax requests, thus it's not need OPTIONS method enabled, besides checking using OPTIONS is problematic as it check only webserver response (nginx work), but not if php-fpm work (which HEAD will check by looking for 200 OK response)

**Comment by williamdes** [comment]
29bcc43956751085274a1cd5985bdcd76850cea3

Is this issue still up to date ?

**Comment by williamdes** [comment]
@emanuelb can you try on latest image since we not not have nginx anymore but apache from the base php image
