### ISSUE TITLE
Missing 4.7.1 tag

### ISSUE THREAD

**Issue by MarvinMenzerath** [phpmyadmin/docker#127]
Hi,

according to https://github.com/phpmyadmin/docker/tags there is no git tag for the recent 4.7.1 release.
This seems to be the reason why https://hub.docker.com/r/phpmyadmin/phpmyadmin/tags/ doesn't list the release.

Could you please add this tag to enable the usage of this exact release?
Thank you!

**Comment by nijel** [comment]
Tag added.
