### ISSUE TITLE
alpine+lighttpd+php7-fpm does not work.

### ISSUE THREAD

**Issue by muhahacz** [phpmyadmin/docker#134]
alpine+lighttpd+php7-fpm does not work. 
For example with -e PMA_ARBITRARY=1, seems that config is not propertly loaded. Any help?

```
FROM alpine:edge

RUN apk update && \
    apk upgrade && \
    apk add --no-cache  curl lighttpd bash php7-fpm php7-pdo_pgsql php7-session php7-mysqli  php7-mbstring php7-xml php7-gd php7-zlib php7-bz2 php7-zip php7-openssl php7-curl php7-opcache php7-json && \
    mkdir -p /var/www/localhost/htdocs/phpmyadmin

RUN apk add --no-cache php7 php7-common php7-iconv php7-json php7-gd php7-curl php7-xml php7-pgsql php7-imap php7-cgi fcgi php7-pdo php7-pdo_pgsql php7-soap php7-xmlrpc php7-posix php7-mcrypt php7-gettext php7$
RUN echo 'include "mod_fastcgi_fpm.conf"' >> /etc/lighttpd/lighttpd.conf
RUN VERSION=`curl -s https://api.github.com/repos/phpmyadmin/phpmyadmin/releases/latest |grep -w "\"name\":" | cut -d '"' -f 4` && curl -sL https://files.phpmyadmin.net/phpMyAdmin/${VERSION}/phpMyAdmin-${VERSI$
RUN curl -so /var/www/localhost/htdocs/phpmyadmin/config.inc.php https://raw.githubusercontent.com/phpmyadmin/docker/master/etc/phpmyadmin/config.inc.php
RUN mkdir -p /etc/phpmyadmin/ && echo 1 > /etc/phpmyadmin/config.secret.inc.php  && chown -R lighttpd:nobody /etc/phpmyadmin  && find /etc/phpmyadmin -type d -exec chmod 750 {} \; && find /etc/phpmyadmin -type f -exec chmod 640 {} \;
RUN    chown -R lighttpd:nobody  /var/www/localhost/htdocs/phpmyadmin/ && find /var/www/localhost/htdocs/phpmyadmin -type d -exec chmod 750 {} \; && find /var/www/localhost/htdocs/phpmyadmin -type f -exec chmod 640 {} \;

EXPOSE 80

CMD php-fpm7 -D && lighttpd -D -f /etc/lighttpd/lighttpd.conf
```

**Comment by nijel** [comment]
1. Why are you using alpine:egde? It's quite possible that something is broken there.
2. Why don't you use our container, but hack your own?
3. We certainly can't support your own container.

PS: At first sight you're missing [this](https://github.com/phpmyadmin/docker/blob/master/Dockerfile#L35), but that's probably not all what is wrong in your Dockerfile.

**Comment by muhahacz** [comment]
1. It will be same result as alpine:latest
2. Im usign lighttpd
3. i does not matter, im asking for advice.

PS.: I have config.inc.php from your docker github here /var/www/localhost/htdocs/phpmyadmin, ( its the default location ) Also tried `sed -i "s@define('CONFIG_DIR'.*@define('CONFIG_DIR', '/etc/phpmyadmin/');@" /www/libraries/vendor_config.php` but i does not work. 

Where should be config.inc.php located? It should be working out of the box with https://raw.githubusercontent.com/phpmyadmin/docker/master/etc/phpmyadmin/config.inc.php, isn it?
