### ISSUE TITLE
use mysql socket

### ISSUE THREAD

**Issue by sgohl** [phpmyadmin/docker#136]
How to use mysql socket? 

`-e PMA_HOST="/var/run/mysqld/mysqld.sock" `

not working. Unknown MySQL server host '/var/run/mysqld/mysqld.sock' (-2)

**Comment by nijel** [comment]
Using socket is not supported right now in the environment variables, you can still override the configuration, see https://docs.phpmyadmin.net/en/latest/setup.html#customizing-configuration

**Comment by s0m30n3** [comment]
I wrote a simple patch to add socket support via PMA_SOCKET and PMA_SOCKETS environment variables.

[0001-Specify-MySQL-socket-file-via-PMA_SOCKET-and-PMA_SOC.patch.txt](https://github.com/phpmyadmin/docker/files/2300617/0001-Specify-MySQL-socket-file-via-PMA_SOCKET-and-PMA_SOC.patch.txt)

**Comment by nijel** [comment]
Would you please mind submitting this as a pull request?

**Comment by o-alquimista** [comment]
Isn't this already fixed by #186?
