### ISSUE TITLE
Enable exposed port to be configurable to run container in host networking mode on a port different than 80

### ISSUE THREAD

**Issue by kanishkdudeja** [phpmyadmin/docker#138]
If I'm running the container with --net=host, it can only be reached on port 80 (ports mapping is disabled when network mode is host).

It would be great to have the possibility to set the port where nginx will listen to with an environment variable (an example is this image: https://github.com/mesoscloud/chronos).

**Comment by sa3dany** [comment]
I looked a bit into this and found this mentioned in the official ngix docker repo

> Out-of-the-box, nginx doesn't support environment variables inside most configuration blocks. But envsubst may be used as a workaround if you need to generate your nginx configuration dynamically before nginx starts.
https://github.com/docker-library/docs/tree/master/nginx#using-environment-variables-in-nginx-configuration

As of now I don't think envsubst is included by default with alpine. We need to include this when building the image:
`RUN apk add --update $RUNTIME_DEPS && apk add --virtual build_deps $BUILD_DEPS && cp /usr/bin/envsubst /usr/local/bin/envsubst && apk del build_deps`

Afterwards we can perform the environment substitution in the run.sh script.

**Comment by KristianWindsor** [comment]
This feature would be extremely helpful.

Port 80 is the default on many images. In the context of a Kubernetes pod, each container must have a unique port – so I cannot run Nginx and PHPMyAdmin within the same pod.

**Comment by KristianWindsor** [comment]
```
FROM phpmyadmin/phpmyadmin
RUN sed -i 's/80/8080/g' /etc/nginx.conf
```
From https://old.reddit.com/r/docker/comments/bula5u/can_i_remap_a_port_in_the_dockerfile/epdoozz/

**Comment by ecdlguy** [comment]
@KristianWindsor: Thanks for the info, It's not really a persistent solution because you have to do that after every container update.

**Comment by williamdes** [comment]
But we do not have a nginx version anymore, right?

**Comment by ecdlguy** [comment]
So it's easier to add this functionality using environment variables?

**Comment by williamdes** [comment]
https://github.com/phpmyadmin/docker/blob/master/apache/Dockerfile

I have to look if it is possible with the image php gives us

**Comment by spantaleev** [comment]
A way to avoid building your own image (to keep things simpler) is to start the image like this:

```
docker run \
-it \
--rm \
--net=host \
--entrypoint=/bin/bash \
phpmyadmin/phpmyadmin:5.0.1 \
-c "sed -i 's/Listen 80/Listen 8080/g' /etc/apache2/ports.conf && /docker-entrypoint.sh apache2-foreground"
```

**Comment by williamdes** [comment]
Thank you for the command
I can integrate changing the port to an ENV variable now

**Comment by williamdes** [comment]
Ref https://github.com/docker-library/php/issues/94#issuecomment-320695125

@J0WI would such a solution be accepted in the entrypoint using an ENV variable ?

**Comment by J0WI** [comment]
Is there a use case to run them in the same pod? For Docker you can also use `-p 8080:80` to expose it on a different port.

**Comment by sergiokessler** [comment]
in Google Cloud Run, there is an already defined env variable `PORT` (default to 8080), and it is supposed your container honor that variable.

**Comment by simann** [comment]
Any updates about this feature?

**Comment by williamdes** [comment]
> Any updates about this feature?

Hi @J0WI 
You have more expertise than me, would you too consider this feature as valid ?

**Comment by J0WI** [comment]
IMHO this shouldn't be changed in every image based on the PHP base image https://github.com/nextcloud/docker/pull/1504#issuecomment-862410960

**Comment by williamdes** [comment]
Done in #369
