### ISSUE TITLE
Hard to handle many servers with `PMA_VERBOSES/PMA_HOSTS/PMA_PORTS`

### ISSUE THREAD

**Issue by kujiy** [phpmyadmin/docker#143]
Since it is hard to handle comma-separated `PMA_VERBOSES/PMA_HOSTS/PMA_PORTS` for more than ten database servers, I'm working on making a tool that makes the comma-separated envs from python dictionary.

> https://gist.github.com/kujiy/6c9fa234e985a5f57ffccc6c9dea5197

Current my envs are like this

```
- PMA_VERBOSES=factory-db,data-db,developers-db,baas-db,main-db,main-test-db,daze-db,vir3,reas-db1,inter01-test-db,shit-dbm,shit-dbs,sat-dbm,sat-dbs
- PMA_HOSTS=10.0.1.117,10.0.1.114,10.0.1.116,10.0.1.125,10.0.1.123,10.0.1.126,10.0.1.127,10.0.1.33,10.0.1.211,10.0.1.41,10.0.1.101,10.0.1.113,10.0.1.101,10.0.1.113
- PMA_PORTS=3306,3306,3306,3306,3306,3306,3306,3306,3306,3306,20036,20037,20136,20137
```

I thought this tool could be in this project, however, it seemed more straight to place an additional server list that is a `php file` in a certain place with docker-compose volume section.

What is a good way to handle lots of servers in this project? I'd like to hear an opinion.

Thank you.

**Comment by nijel** [comment]
You can use PHP file as well to define the configuration, see https://docs.phpmyadmin.net/en/latest/setup.html#customizing-configuration (I've just added example for your case there).
