### ISSUE TITLE
Docker User config does not get recognized.

### ISSUE THREAD

**Issue by mstenz** [phpmyadmin/docker#146]
Hi, 
i have created a docker service with the following command:
> docker service create \
--name phpmyadmin \
--replicas 1 \
--network internal \
--mount type=bind,source=/storage/docker1/phpmyadmin/config.user.inc.php,target=/etc/phpmyadmin/config.user.inc.php \
phpmyadmin/phpmyadmin:4.7

the container is running, but it shows a normal login page and only allows to use default "db" as hostname, even I see that my config is available within the container:

> $i = 0;
$i++; // server 1 :
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['verbose']   = 'mariadb';
$cfg['Servers'][$i]['host']      = 'mariadb';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'xxxxxxxxxx';

Any idea why the file get not applied?

**Comment by nijel** [comment]
Don't you miss the `<?php` at top of the file?

**Comment by mstenz** [comment]
@nijel no, i have only pasted a part of the file

**Comment by crzdeveloper** [comment]
I solved similar problem by setting the correct permissions to `/etc/phpmyadmin/config.user.inc.php`. 
phpMyAdmin runs as nobody:nobody, so the permissions can be 0644

`chmod 0644 /etc/phpmyadmin/config.user.inc.php`
