### ISSUE TITLE
Version Tags

### ISSUE THREAD

**Issue by wdch-nseeley** [phpmyadmin/docker#15]
Any chance of taging versions on docker hub?

I was trying to use that new feature (#13, #12 PmaAbsoluteUri) and couldn't understand why it wasn't working. Turns out this feature is incredibly new and not part of my 7 day old image. Ugh!

But anyways, I'm glad its implemented.  :)

**Comment by nijel** [comment]
Not sure how to do that ... Docker hub builds every commit, it's all automated.

**Comment by nijel** [comment]
Added first tag and I will try to remember pushing tags now.
