### ISSUE TITLE
Security release 4.7.8 missing on docker hub

### ISSUE THREAD

**Issue by ViceIce** [phpmyadmin/docker#150]
Please push the 4.7.8 release to the docker hub.

Regards
Michael

**Comment by nijel** [comment]
It was there, just the tag was missing. I've just pushed that as well.

**Comment by ViceIce** [comment]
What about the `latest` tag? Should be updated too?

**Comment by nijel** [comment]
That should update automatically (it's using latest tagged release). As you can see `latest`, `4.7` and `4.7.8-1` are in sync:

![screenshot-2018-2-22 phpmyadmin phpmyadmin - docker hub](https://user-images.githubusercontent.com/212189/36567736-c060c2b6-1827-11e8-99d1-809e11f8b86b.png)

**Comment by ViceIce** [comment]
As i looked it wasn't updated. Thanks.

**Comment by nijel** [comment]
AFAIK the builds are processed sequentially on Docker Hub, so it takes some time for all of them to appear.
