### ISSUE TITLE
Possiblity to configure the phpMyAdmin configuration storage

### ISSUE THREAD

**Issue by Farfaday** [phpmyadmin/docker#151]
Hi,
Would it be okay to add the possibility to configure the phpMyAdmin configuration storage via Env vars ?

I would add the following vars:
```
PMA_CONTROLHOST
PMA_CONTROLPASS
PMA_CONTROLPORT
PMA_CONTROLUSER
PMA_PMADB
```

I can work on providing a PR for this.
Thanks!

**Comment by nijel** [comment]
Sounds like an useful addition.

**Comment by nijel** [comment]
Fixed by https://github.com/phpmyadmin/docker/pull/152.

**Comment by trickert76** [comment]
Sorry, but I miss the configuration option to be documented. You need to know, that PMA_PMADB must be defined as environment variable. Could you please document the feature.

**Comment by ravensorb** [comment]
Question -- should the pma database be automatically created with the correct tables if I set these? The reason for the question is that as of 5.0.2 I am not able to get them to auto create within a docker container - See thread in #159

**Comment by williamdes** [comment]
> Question -- should the pma database be automatically created with the correct tables if I set these? The reason for the question is that as of 5.0.2 I am not able to get them to auto create within a docker container - See thread in #159

I would say, only if an ENV explicitly says that

**Comment by williamdes** [comment]
> Sorry, but I miss the configuration option to be documented. You need to know, that PMA_PMADB must be defined as environment variable. Could you please document the feature.

Done ;)
https://github.com/phpmyadmin/docker#readme
