### ISSUE TITLE
Warning about TempDir in 4.8.0 image

### ISSUE THREAD

**Issue by hemberger** [phpmyadmin/docker#156]
I'm seeing the following warning after updating to the phpMyAdmin 4.8.0 docker image:
```
The $cfg['TempDir'] (./tmp/) is not accessible. phpMyAdmin is not able to cache templates and will be slow because of this.
```
Is this something we should be responsible for creating ourselves and mounting into the container, or is this an issue with the permissions set in the image?

Thanks for any help you can provide!

**Comment by ibennetch** [comment]
I think this should be fixed. I think it was an oversight with the Docker image when the template engine was added for 4.8.0.

**Comment by nijel** [comment]
Fixed by https://github.com/phpmyadmin/docker/pull/155
