### ISSUE TITLE
edge-4.8 not updated

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/docker#157]
It appears to me as if the edge-4.8 tag is not updating.

**Comment by nijel** [comment]
The root cause is that snapshots are not being updated, therefore the docker images can not be updated. Additionally there is problem that the edge-4.8 branch is not up to date.

**Comment by nijel** [comment]
There were several problems with snapshots (missing yarn, old PHP version, wrong composer configuration), but that is now sorted out and it includes 5.0 snapshots: https://www.phpmyadmin.net/downloads/

The edge-4.8 image is just being built: https://hub.docker.com/r/phpmyadmin/phpmyadmin/builds/bmyyoijznmugitjnzwemccw/
