### ISSUE TITLE
Broken tests due #165?

### ISSUE THREAD

**Issue by J0WI** [phpmyadmin/docker#169]
Tests seems to be broken since #165.

**Comment by nijel** [comment]
It doesn't seem to be related to #165, the actual error is that it fails to connect to MySQL:

> mysqli_real_connect(): The server requested authentication method unknown to the client [caching_sha2_password]
> mysqli_real_connect(): (HY000/2054): The server requested authentication method unknown to the client

Probably some change in the PHP container as it affects both MariaDB and MySQL servers.

**Comment by nijel** [comment]
See also https://github.com/phpmyadmin/phpmyadmin/issues/14220

**Comment by J0WI** [comment]
That seems to be true for MySQL, but MariaDB still fails in the `docker-compose.testing.yml` test.

**Comment by J0WI** [comment]
See #175

**Comment by nijel** [comment]
Fixed by https://github.com/phpmyadmin/docker/pull/175

**Comment by J0WI** [comment]
@nijel do you have an idea about the broken MariaDB 10.3 test?

**Comment by nijel** [comment]
What is the failure there?

**Comment by J0WI** [comment]
See https://travis-ci.org/phpmyadmin/docker/jobs/391318946#L1977-L1983

**Comment by nijel** [comment]
I've created https://github.com/phpmyadmin/docker/issues/176 for that.
