### ISSUE TITLE
Possibility to deactivate SSL connection

### ISSUE THREAD

**Issue by gervaud** [phpmyadmin/docker#170]
Hello,
I upgraded phpmyadmin container from 4.6.6-2 to 4.8.1 and I get this error/warning message on the phpmyadmin login page:

>  There is mismatch between HTTPS indicated on the server and client. This can lead to non working phpMyAdmin or a security risk. Please fix your server configuration to indicate HTTPS properly.

I don't use SSL between phpmyadmin server and the db server because it is in a secured AWS environment.
Is there a way to configure the container to deactivate this SSL check ?

**Comment by J0WI** [comment]
I assume you're searching for this?
https://docs.phpmyadmin.net/en/latest/config.html#cfg_Servers_ssl
https://github.com/phpmyadmin/docker#adding-custom-configuration

**Comment by ibennetch** [comment]
This actually looks like another instance of https://github.com/phpmyadmin/phpmyadmin/issues/14184 to me.

**Comment by RichPC** [comment]
I'd been using the phpmyadmin package installed by ubuntu apt on 18.04. That version had bugs to do with a count function and parenthesis not closing properly. So I decided to remove the symlink to /var/www/pma and install phpmyadmin by wget download instead, again at /var/www/pma. The site opened but was showing:

> There is mismatch between HTTPS indicated on the server and client. This can lead to non working phpMyAdmin or a security risk. Please fix your server configuration to indicate HTTPS properly.

and had no css styling applied.

Turned out the ubuntu package had changed the way config is done for phpmyadmin.

After running

`sudo apt purge phpmyadmin`

and refreshing my browser cache, the manual (downloaded) install worked.

**Comment by romanmm** [comment]
> The error message indicates that the error is related to the HTTPS connection, so it doesn't have anything to do with the (un-) encrypted database connection. Actually, it is based on how you access phpMyAdmin.
> 
> In my case I was running phpMyAdmin behind a SSL termination proxy, so phpMyAdmin does not recognize that it is a secure request, even though it actually is. And because of that mismatch, phpMyAdmin is showing this warning, see [here](https://github.com/phpmyadmin/phpmyadmin/blob/f8cfd096b2766997f482e2e0e2865611f379c08e/js/functions.js#L4785)
> 
> I fixed it by setting the `PMA_ABSOLUTE_URI` environment variable to the actual URL, according to the [README](https://github.com/phpmyadmin/docker#usage-behind-reverse-proxys):
> 
> > Set the variable PMA_ABSOLUTE_URI to the fully-qualified path (https://pma.example.net/) where the reverse proxy makes phpMyAdmin available.


You are absolutely right! The reason of the warning is reverse proxy (in my case, Nginx) that receives HTTPS request but forward the request to PhpMyAdmin as plain HTTP.
I've added this row to environments inside docker-compose.yml that defines PhpMyAdmin:
**PMA_ABSOLUTE_URI: "https://pma.example.com/"**
and HTTP warning has disappeared.

**Comment by harshit-saini** [comment]
I am running wamp and I am getting the same error. what should I do

**Comment by emmanuelkolawole4** [comment]
hello, i just started using laragon and i'm getting the error:
There is mismatch between HTTPS indicated on the server and client. This can lead to non working phpMyAdmin or a security risk. Please fix your server configuration to indicate HTTPS properly.

please could someone walk me through solving this problem?

**Comment by williamdes** [comment]
@emmanuelkolawole4 I was thinking you where using docker since you commented on https://github.com/phpmyadmin/docker and not https://github.com/phpmyadmin/phpmyadmin

You should have a look to https://github.com/phpmyadmin/phpmyadmin/issues/14184

**Comment by emmanuelkolawole4** [comment]
@williamdes oh alright, i'll do just that. thank you!

**Comment by aschuch247** [comment]
It seems the message can be ignored, see phpmyadmin/phpmyadmin#15200.

**Comment by daniela-waranie** [comment]
Looks like the original issue (from 2018) was resolved and all "free riders" also got a valid answer.

Lets close this ticket now.
