### ISSUE TITLE
Broken waiting for db server in tests

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/docker#176]
The code for waiting for database server to be up is not really working reliably. The problem is probably in using curl instead of speaking native mysql protocol.

Example test failure:

https://travis-ci.org/phpmyadmin/docker/jobs/391318946#L1977

Related code:

https://github.com/phpmyadmin/docker/blob/d53771b561093b2993c939424dd6560ea1c12454/testing/test-docker.sh#L30-L49

It should probably rather use mysql client instead of curl.

**Comment by williamdes** [comment]
Seems to be fixed
