### ISSUE TITLE
point latest to 4.8.1

### ISSUE THREAD

**Issue by kenden** [phpmyadmin/docker#177]
The latest release in this git repo is `4.8.1`, yet image `latest` in dockerhub is not the same as image 4.8.1.

Or if git release `4.8.1` is not stable, please indicate it (`4.8.1-beta`, `4.8.1-rc`...) so users do not expect latest to be it.

**Comment by ibennetch** [comment]
Latest is indeed 4.8.1. I'm not certain off hand why latest isn't updated correctly. Maybe @nijel has some idea about this.

Thanks for the report, we'll look in to it.

**Comment by nijel** [comment]
Both were built at same time, so they should be same:

https://hub.docker.com/r/phpmyadmin/phpmyadmin/builds/b7jhubuhb6cht74nghgllpv/
https://hub.docker.com/r/phpmyadmin/phpmyadmin/builds/bpt3ukjzyyccefyafkfdbcg/

**Comment by kenden** [comment]
They have different image ids though
```
phpmyadmin/phpmyadmin                                        latest                                     4bdc31ab2ded        2 weeks ago         164MB
phpmyadmin/phpmyadmin                                        4.8.1                                      9a32dd8baf4a        2 weeks ago         163MB
```

**Comment by nijel** [comment]
Maybe some of the deps was rebuilt between the builds. I have no clue how to copy images, so both latest and release images are built separately.

**Comment by kenden** [comment]
@nijel does this help?
https://docs.docker.com/engine/reference/commandline/tag/

`docker tag phpmyadmin/phpmyadmin:4.8.1 phpmyadmin/phpmyadmin:latest`

Then 
```
$ docker push phpmyadmin/phpmyadmin:4.8.1 
$ docker push phpmyadmin/phpmyadmin:latest
```

**Comment by nijel** [comment]
So far everything is built on docker hub, we don't push anything manually...

**Comment by J0WI** [comment]
This seems to be obsolete.
