### ISSUE TITLE
DNS name resolution not working

### ISSUE THREAD

**Issue by jn-simonnet** [phpmyadmin/docker#179]
Whether with latest tag (4.8) or 4.7 or 4.6, I found that it is possible to connect to a mysql docker instance through the IP address. However, using a DNS name does not work and results in a timeout. It seems that names do not resolve. Missing the required libs for name resolution in the container ?

**Comment by jn-simonnet** [comment]
OK. Found the root cause of the problem. The issue is that the resolv.conf file points to DNS servers 8.8.8.8 and 8.8.4.4. Hence when resolving a local network host, there is no chance that it gets resolve, we need to point to local DNS servers instead of INternet ones.
Solution is to edit (Case of UBuntu host) the /etc/default/docker file to add DNS servers in place of the default ones.
THis issue is not specific to phpmyadmin container.

**Comment by magdsnail** [comment]
you can try it .   
add Environment variables summary .  PMA_ABSOLUTE_URI
https://hub.docker.com/r/phpmyadmin/phpmyadmin/

**Comment by williamdes** [comment]
You seem to have solved the issue @jn-simonnet 
Closing, post here if you did not solve the issue.
