### ISSUE TITLE
Use port 80 instead of port 8080

### ISSUE THREAD

**Issue by RickWieman** [phpmyadmin/docker#18]
Just a thought: wouldn't it make sense to expose port 80 instead of port 8080? A user can always map any exposed ports to whatever he likes, e.g. `-p 8080:80`, and as this is in fact a Docker container running a web application, doesn't it sound logical to use the http port for that? Or were there practical considerations for using port 8080 instead?

If you agree, I'm willing to open a PR, but let's discuss this first.

**Comment by nijel** [comment]
Probably there was not much thinking behind this. So if you think breaking compatibility is not an issue, feel free to open PR.

**Comment by RickWieman** [comment]
Naturally, everyone using this container should change their port mapping (e.g. when used in automated deployment, compose, or whatever) once after that PR. Do you think that's too much of an issue, or can we consider that as a one-time inconvenience?

**Comment by nijel** [comment]
I'm not really sure, I don't use Docker for anything important so it would be minor hassle for me. But I think it's reasonable change.

**Comment by rhcarvalho** [comment]
Hey, just wanted to give some feedback as I was trying to use this image with OpenShift.

> as this is in fact a Docker container running a web application, doesn't it sound logical to use the http port for that? Or were there practical considerations for using port 8080 instead?

Dan Walsh explains how containers don't contain:
https://youtu.be/kvoxC_iql9g?t=917

It's generally a bad idea to run containers as root, and therefore 8080 and being able to run as an arbitrary unprivileged user is better than running on port 80.

Some more written tips here:

http://www.projectatomic.io/docs/docker-image-author-guidance/
https://docs.openshift.com/enterprise/3.2/creating_images/guidelines.html#use-uid


So yeah, there was nothing wrong with using 8080, and it was actually a better choice IMHO.

**Comment by nijel** [comment]
Looking at some other web apps, they seem to use 80 as well:

* https://hub.docker.com/_/drupal/
* https://hub.docker.com/_/wordpress/
* https://hub.docker.com/_/joomla/

So this really seems to be common practice these days.

**Comment by rhcarvalho** [comment]
@nijel I acknowledge you'll find that in DockerHub, rather more frequently than not. Doesn't mean that's the best idea from a security stand point :-)

I attempted to provide "practical considerations" to the question from @RickWieman.

While there's no benefit in running on port 80 vs. any other port, listing on :80 requires root privilege, which prevents users of the image to run as non-root, would they choose to do it:

```console
$ docker run --rm -u nobody phpmyadmin/phpmyadmin
+ [ ! -f /www/config.secret.inc.php ]
/run.sh: line 1: can't create /www/config.secret.inc.php: Permission denied
+ cat
+ exec php -S 0.0.0.0:80 -t /www/ -d upload_max_filesize=64M -d post_max_size=64M -d max_input_vars=2000
[Mon May 23 08:20:20 2016] Failed to listen on 0.0.0.0:80 (reason: Permission denied)
```

Several articles on container security, as in the links I posted earlier, suggest running containers as non-root.

**Comment by nijel** [comment]
There is a benefit - you can access it directly in browser without need to specify the port.

However I'm not really docker user, so I have no clue what is best solution. On the other side I don't want to change ports there and back several times, so I'd really like to see some kind of consensus before doing another change. And that consensus currently seems to be using port 80.

**Comment by arikardnoir** [comment]
ERROR: for e53d0530f50b_laradock_phpmyadmin_1  Cannot start service phpmyadmin: driver failed programming external connectivity on endpoint laradock_phpmyadmin_1 (9c1b7be8de226328963e74142f6fb0be50874c30027aee39290448ae3890387b): Error starting userland proxy: Bind for 0.0.0.0:8080 failed: port is already allocated



how can't I fix this? on Mac?

**Comment by svaroqui** [comment]
Hi , 

It does not sound good to use port 80 each docker application should have it's own port. 
In some docker service definition i should be able to share network of a top level container with multiple containers pack in a single service. There is a good chance that phpmyadmin shared across services with an existing application web service   

What is a common practice is to expose via env variable the tcp port  used by nginx 

Tx
