### ISSUE TITLE
Failed to load phpMyAdmin configuration

### ISSUE THREAD

**Issue by baotongshi** [phpmyadmin/docker#185]
I run the MySQL.5.7 container and phpMyAdmin.4.7 container on my vm by using the below command,

- docker run  -p 3306:3306 -v /data/appdata:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=xxx --name mysqlsvr -d mysql:5.7
- docker run  --link mysqlsvr:db -p 8080:80 -d phpmyadmin:4.7

but when I access the phpMyAdmin web, I got the error
_Failed to load phpMyAdmin configuration (./../etc/phpmyadmin/config.inc.php:3): require(): Failed opening required '/etc/phpmyadmin/config.secret.inc.php' (include_path='.:/usr/local/lib/php')_

**Comment by williamdes** [comment]
@baotongshi did you check this was not a permission issue on your side ?
