### ISSUE TITLE
phpmyadmin docker 4.8.3 is not support mysql_native_password to connect mysql 8?

### ISSUE THREAD

**Issue by m2nlight** [phpmyadmin/docker#188]
The phpmyadmin:latest cann't connect mysql:latest(docker).
The mysql with `mysql_native_password `, and phpmyadmin:4.8.2 is OK.
Maybe, who can give an envionment variable of docker to switch msyql auth plugin?
Thx~

**Comment by williamdes** [comment]
@m2nlight Sorry for the very late response, but we do not manage mysql users creation for the docker image.
Maybe you should ask the mysql docker image to implement it (that would save a lot of time instead of changing plugins manually at first boot)
