### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by westhouseit** [phpmyadmin/docker#189]
I've tried so many different angles to get this resolved and just can't see what else could be done. Here's my setup:

    docker run -d \
        --name phpmyadmin \
        --restart always \
        -e VIRTUAL_HOST=pma.localhost \
        -e PMA_ARBITRARY=1 \
        -e PMA_ABSOLUTE_URI=http://pma.localhost \
        -v ~/pma/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php \
        phpmyadmin/phpmyadmin:4.8.1

I've tried with 4.7, 4.8.1, 4.8.2, and 4.8.3. 

I follow this with

    docker network connect phpmyadmin phpmyadmin

~/pma/config.user.inc.php is owned root:root and contains 

    <?php
    ini_set("upload_max_filesize", "100M");
    ini_set("post_max_size", "100M");

Importing a working 38.3MB .sql that's gzipped to 3.8MB results in an nginx error:

    413 Request Entity Too Large

I've gone trawling through a shell console of the container and can't fix it no matter what I do. Just in case I've messed up anything I completely recreate the container after everything I try.

**Comment by nijel** [comment]
The limit of the image is supposed to be 512 MB:

https://github.com/phpmyadmin/docker/blob/b1e2062fb4628a595f7dd532b91acd4699654462/etc/nginx.conf#L41

https://github.com/phpmyadmin/docker/blob/b1e2062fb4628a595f7dd532b91acd4699654462/php.ini#L6-L7

**Comment by westhouseit** [comment]
I can find /etc/nginx.conf via console and it matches your line 41 above. But there's no php.ini at root in the 4.8.2 image. Is it possibly moved somewhere as part of the startup process?

**Comment by westhouseit** [comment]
Ok, so I think we're getting somewhere now. The 4.8.2 image is missing the php.ini even though it's in the repository commit that's tagged 4.8.2. Adding it manually to the image and restarting it fixes the issue.

This doesn't resolve why versions before 4.8.2 aren't working since they match the repo which shows no php.ini at root.

**Comment by westhouseit** [comment]
Significant commit: https://github.com/phpmyadmin/docker/commit/b369d770dda59ba8564915ab830d91d32e043254

**Comment by Herz3h** [comment]
I have the same issue, how do I change the upload_max_filesize and post_max_size variables in this docker image ??

**Comment by williamdes** [comment]
Implemented in #261 :tada:

**Comment by CaliforniaMountainSnake** [comment]
You can use `UPLOAD_LIMIT` environment variable:

![Screenshot_20210304_160233](https://user-images.githubusercontent.com/44233829/109967956-1ffd4d00-7d03-11eb-923c-998aa5ca9e95.png)


See this:
https://stackoverflow.com/a/60146255/10452175

**Comment by BarnumD** [comment]
The above `UPLOAD_LIMIT` variable is not working on phpmyadmin:latest, or phpmyadmin:5.2.1-apache as of the time of this post.

**Comment by williamdes** [comment]
> The above `UPLOAD_LIMIT` variable is not working on phpmyadmin:latest, or phpmyadmin:5.2.1-apache as of the time of this post.

That makes no sense, please open a new issue so we can check
