### ISSUE TITLE
php-fpm crash with "Bus error"

### ISSUE THREAD

**Issue by fvigotti** [phpmyadmin/docker#193]
this happens always but only on certain conditions,
using docker 18.03 , and kubernetes 1.11.3 , on ubuntu 18.04
when the container is started from kubernetes , php-fpm crash immediately with core dump  when launched from docker it works ( no special privileges )

anyway the problem is this package : **opcache** , (i've build the image manually from a running kubernetes pod testing php-fpm after each step of installation ) and the php-fpm fail to execute ( even with `php-fpm --version` or `php-fpm --help` ) when the package opcache is installed 

It's necessary? I suggest to remove it.. and hope to have helped others in my situation,

Regards,
Francesco

**Comment by lzjohnny** [comment]
I have the same problem, when I use docker and kubernetes, and enable php opcache and set opcache.huge_code_pages=1 PHP will crash. I have no idea about it.

**Comment by williamdes** [comment]
You could use another variant, have a look at new tags on docker hub https://hub.docker.com/r/phpmyadmin/phpmyadmin/tags

**Comment by williamdes** [comment]
I am closing the issue since it is old
Comment if you think it is still an issue

**Comment by DrissiReda** [comment]
I still have this issue today, using php-fpm 7 with kubernetes 1.21 and containerd 1.4.4

**Comment by williamdes** [comment]
> I still have this issue today, using php-fpm 7 with kubernetes 1.21 and containerd 1.4.4

Could you please share some configs ?

**Comment by DrissiReda** [comment]
> Could you please share some configs ?
What configs do you need? 
disabling hugepages works... But I'd like to keep them

**Comment by williamdes** [comment]
> disabling hugepages works

Then it's probably better to open an issue on a bug tracker for the php fpm project as this will be out of the scope of phpMyAdmin ;)
