### ISSUE TITLE
themes folder mount changed

### ISSUE THREAD

**Issue by Coding-Kiwi** [phpmyadmin/docker#203]
In the newest docker release 4.8.4 the themes folder can no longer be mounted to /www/themes/customtheme as specified in the documentation, it has to be /var/www/html/themes/customtheme

**Comment by spawnia** [comment]
It's not even possible to mount it anymore - as the init process just copies over that location.

Had to `COPY` it in within a Dockerfile.

**Comment by williamdes** [comment]
@spawnia Does the latest version stil require that you add `COPY` ?

**Comment by ibennetch** [comment]
We appear to have moved the location of the web root in the docker image at some point, but failed to update the documentation.

Could you please try again? I've just tested several configuration variations and have had good luck with this so if you're still having trouble, it would be helpful to know more about the exact commands you're using.

**Comment by spawnia** [comment]
> @spawnia Does the latest version stil require that you add `COPY` ?

Yes, as the themes are not included by default.

```Dockerfile
COPY fallen /usr/src/phpmyadmin/themes/fallen
```

**Comment by williamdes** [comment]
> In the newest docker release 4.8.4 the themes folder can no longer be mounted to /www/themes/customtheme as specified in the documentation, it has to be /var/www/html/themes/customtheme

Since https://github.com/phpmyadmin/docker/commit/662b82d27e87722826ce4c40d2db83553e79c898 (#198)

See #398 where I will update the docs. It's too bad this issue got closed and lost attention
