### ISSUE TITLE
[compose] Name does not resolve

### ISSUE THREAD

**Issue by ibasaw** [phpmyadmin/docker#204]
docker-compose.yml v2
```
    phpmyadmin:
        restart: always
        image: phpmyadmin/phpmyadmin
```

```
mysqli_real_connect(): php_network_getaddresses: getaddrinfo failed: Name does not resolve
 mysqli_real_connect(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name does not resolve
```

i can browse the login page, when i enter credential root i got this error
My symfony project can use the database with same credentials, so this is not a credentials error

**Comment by williamdes** [comment]
@ibasaw Please have a look at https://github.com/phpmyadmin/docker/blob/master/docker-compose.testing.yml
We use links but you can use the `PMA_HOST` env variable if the container is in the same network than the database
