### ISSUE TITLE
Nginx reverse proxy to phpmyadmin is not working

### ISSUE THREAD

**Issue by SubrataM3** [phpmyadmin/docker#210]
**Docker Image version:**
4.8.5 (using the latest tag)

**Nginx configuration:**
Using the same configuration that is supposed to work as per the comments of other users here.
```
location /phpmyadmin {
                proxy_pass http://phpmyadmin/;
                proxy_redirect off;
                proxy_set_header Host $host;
}
```
**Docker-compose**
I have set correct environment variable using the following URL
`- PMA_ABSOLUTE_URI=https://sub.domain_name.com/phpmyadmin/`

**Issues**

1. The page is not loading correctly (Please check attached image) (latest version)
![shot_190219_014516](https://user-images.githubusercontent.com/15718377/52974576-10469080-33e8-11e9-8f31-4071015f7702.png)
2. Whenever the env variable is set in docker-compose I get following warning.

> There is a mismatch between HTTPS indicated on the server and client. This can lead to non-working phpMyAdmin or a security risk. Please fix your server configuration to indicate HTTPS properly.

I am sure the PMA_ABSOLUTE_URI is correctly set.

3. After submitting login I get  **404 Not Found**.

4. I have also tried earlier versions like 4.7 and 4.6. Those were just returning a blank page, you can see failed elements in the following screenshot.
![image](https://user-images.githubusercontent.com/15718377/52974937-58b27e00-33e9-11e9-8dca-52f8ddc21096.png)

Kindly help me with this issue. You can also send instructions to debug this.
Thank you.

**Comment by Chrisly3ear** [comment]
Same.

**Comment by SubrataM3** [comment]
Hi, 

I have actually got this issue fixed. I can explain what was happening.

Here is my updated & working configuration.
```
location ~ ^/phpmyadmin/ {
	rewrite ^/phpmyadmin(/.*)$ $1 break;
    proxy_pass http://phpmyadmin;
}
```

Issue 1 : 
Nginx selects "location block with regex" before "location with just prefix path". I had another location block like the following which was basically capturing all other php file request.
> location ~ [^/]\.php(/|$)
As you can see (Image of Issue 1) only PHP files were failing to load which was actually getting captured by the general php location block. 

Issue 2: This was happening because of PHP files were failing to load.

I hope this helps others.

**Comment by tenshiAMD** [comment]
@SubrataM3 can you share to us your config file? Thanks in advance.

**Comment by SubrataM3** [comment]
> @SubrataM3 can you share to us your config file? Thanks in advance.

I think already shared my config on the above post? which config you are talking about?

**Comment by chendelin1982** [comment]
I use below and can access 
```
  location /phpmyadmin/ {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto  $scheme;
    proxy_set_header X-Forwarded-For    $remote_addr;
    proxy_set_header X-Real-IP		$remote_addr;
    proxy_pass       http://phpmyadmin:80;
    rewrite ^/phpmyadmin(/.*)$ $1 break;
  }
```
