### ISSUE TITLE
Stable version 4.8.5 from january not in latest branch

### ISSUE THREAD

**Issue by Nimrod-666** [phpmyadmin/docker#218]
Hi,
is there a reason why version 4.8.5 is not included in latest? The version there is 4.8.4 and i'm wondering why it is like that since january, where 4.8.5 was released.

**Comment by ibennetch** [comment]
I'm a little confused, because I think it is in latest.

I just started a new docker container from the latest tag and my phpMyAdmin is saying it's version 4.8.5.

Unfortunately, I'm not that familiar with Docker to know exactly what could be wrong.

**Comment by J0WI** [comment]
`latest` points to `4.8.5` for me.

**Comment by Nimrod-666** [comment]
Here is my Compose-File:
![2019-05-05 13_25_51-root@h2817249_ ~_docker_blakylle_de](https://user-images.githubusercontent.com/46351035/57193255-5caa6280-6f39-11e9-9b8e-5eb8754933a0.png)
And here the Version (german language)
![2019-05-05 13_21_31-](https://user-images.githubusercontent.com/46351035/57193256-5caa6280-6f39-11e9-988d-aadba0680128.png)

I did several "docker-compose build --pull" and "docker-compose up -d" commands, but the version don't change. It stays 4.8.4.

**Comment by J0WI** [comment]
`docker-compose build --pull` has no effect for prebuilt images. Try `docker-compose pull` or `docker pull phpmyadmin/phpmyadmin`.

**Comment by Nimrod-666** [comment]
Oh i see! Thank you!
