### ISSUE TITLE
session_start(): Failed to read session data: files (path: /sessions)

### ISSUE THREAD

**Issue by spark8103** [phpmyadmin/docker#226]
This repository contains only Docker integration of phpMyAdmin.

Please do not report bugs in phpMyAdmin itself here, use
<https://github.com/phpmyadmin/phpmyadmin/issues> instead.

open web is error.
`
Error during session start; please check your PHP and/or webserver log file and configure your PHP installation properly. Also ensure that cookies are enabled in your browser.

session_start(): open(SESSION_FILE, O_RDWR) failed: No such file or directory (2)

session_start(): Failed to read session data: files (path: /sessions)
`

**Comment by spark8103** [comment]
docker info
`Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        e8ff056
 Built:             Thu May  9 23:18:36 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e8ff056
  Built:            Thu May  9 22:53:57 2019
  OS/Arch:          linux/amd64
  Experimental:     false`

**Comment by williamdes** [comment]
@spark8103 can you provide more details on how you start the docker image ?
docker-compose ?
command line ?

**Comment by williamdes** [comment]
@spark8103 Can you send your configuration or command line ?
please check the file permissions for the docker volume

**Comment by Hassanzadeh-sd** [comment]
you have to set permission for tmp directory `chmod 777 tmp`

**Comment by shouhuori** [comment]
get same error

**Comment by shouhuori** [comment]
get this error
```
Error during session start; please check your PHP and/or webserver log file and configure your PHP installation properly. Also ensure that cookies are enabled in your browser.

session_write_close(): write failed: No space left on device (28)

session_write_close(): Failed to write session data (files). Please verify that the current setting of session.save_path is correct ()
```

**Comment by williamdes** [comment]
@shouhuori did you declare the sessions volume ?
You can have a look to https://github.com/wdesportes/phpmyadmin-local-setup/blob/master/docker-compose.yml#L592 and the files in the root folder :)

**Comment by shouhuori** [comment]
Thanks your replay.I soleved this.

**Comment by ynov-ikftree** [comment]
@shouhuori how u solve this plz!

**Comment by williamdes** [comment]
> @shouhuori how u solve this plz!

What is your docker compose file?

**Comment by ynov-ikftree** [comment]
version: '3.9'

services:
  php-env:
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:80

  mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

**Comment by ynov-ikftree** [comment]
my docker installed in linux VM

**Comment by ynov-ikftree** [comment]
when i work with docker desktop windows i dont have no probleme

**Comment by ynov-ikftree** [comment]
all working good but the probleme is i can see orther pages without authentifie
erreur : warning : undefined array key "login" in/var/www/html/home.php

**Comment by williamdes** [comment]
> all working good but the probleme is i can see orther pages without authentifie erreur : warning : undefined array key "login" in/var/www/html/home.php

Sorry this is not related to phpMyAdmin. We have no home.php file

**Comment by ynov-ikftree** [comment]
the session_start() in my page home.php doen't work to verifie if the client authentifie or not

**Comment by ynov-ikftree** [comment]
this probleme only in docker linux

**Comment by ynov-ikftree** [comment]
when i work with xampp or docker in windows i dont have this probleme and all so when i want to open home page without authentifie i can't -> header('Location: index.php');

**Comment by MaG21** [comment]
If you use NGINX on amazon Linux 2023, you may want to change the permissions so NGINX (php-fpm) can have write access, like this:

```bash
sudo chown root:nginx -R /var/lib/php/session
```
