### ISSUE TITLE
Docker repo missing version tags

### ISSUE THREAD

**Issue by johan-smits** [phpmyadmin/docker#229]
### To Reproduce

The docker repo https://hub.docker.com/r/phpmyadmin/phpmyadmin/tags does not contain all release tags. It only has 4.9 and in the past the minor version was also available.

### Expected behavior

Have a 4.9.0.and a 4.9.0.1 tag

**Comment by williamdes** [comment]
Duplicate of #256

**Comment by ibennetch** [comment]
This should now be resolved, fixed by #259.
