### ISSUE TITLE
Discussion: Designate Docker tags moving forward

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/docker#231]
We should decide on which tags we'll offer.

I've taken some hints from [Alpine](https://hub.docker.com/_/alpine), [Apache](https://hub.docker.com/_/httpd), [PHP](https://hub.docker.com/_/php), and [WordPress](https://hub.docker.com/_/wordpress) (many as suggested by @J0WI in #200) and have this to propose. Note that, even though currently we're at phpMyAdmin 4.9.0.1, I'm pretending it's 4.9.0 to make this easier to read).

* Base/default tags (built with Apache)
  * `edge` (development version built off a daily snapshot, currently 5.0.0-dev)
  * `4.9.0`, `4.9`, `4`, `latest-apache`, `latest` (phpMyAdmin 4.9.0)
* FPM
  * `edge-fpm` (development version from daily snapshot)
  * `4.9.0-fpm`,`4.9-fpm`, `4-fpm`, `latest-fpm` (phpMyAdmin 4.9.0)
* FPM-Alpine
  * `edge-fpm-alpine` (development version from daily snapshot)
  * `4.9.0-fpm-alpine`,`4.9-fpm-alpine`, `4-fpm-alpine`, `latest-fpm-alpine` (phpMyAdmin 4.9.0)

Under my proposal, the following current tags would be deprecated:
* `edge-4.9` (4.9.1-dev snapshot, built from QA_4_9), mostly because I don't foresee an instance where a user would want a development version but not 'master'; either they want the bleeding edge or they want stability.
* `fpm`, `fpm-alpine` (currently an alias for master phpMyAdmin build with FPM or FPM-Alpine, just added when I merged #200 and not yet highly advertised).

In the past, we've build specific Docker releases that are incremented; such as `4.8.0-3`. I *think* we won't need to do that as we can just push any mid-stream changes as a new Docker release of the same version (4.8.0). The `-3` seems to be not a very standard Docker syntax.

This is obviously a large number of tags. I'm not fond of this, but think this is probably best and will just take some careful rule-building on DockerHub. I also don't personally see a need to maintain patch-level tags (4.9.0) and would prefer only minor-version tags (4.9). I'm not sure if that's keeping with Docker-style tags, though

**Comment by J0WI** [comment]
I'd prefer `fpm` and `fpm-alpine` without the `latest-` prefix to be consistent with other containers.

Once #56 is solved the tags will be generated by #216, but I'm not sure about the `edge` tags. I think it's easier to just mount the sources from https://github.com/phpmyadmin/phpmyadmin

**Comment by J0WI** [comment]
@williamdes @ibennetch #216 has been merged, so it would be great if you could publish this to the library (#56).

**Comment by shinebayar-g** [comment]
Docker image doesn't have `4.9.0.1` or `4.9.1` tags which is I expected to have there. Having only `4.9` looks incorrect.

**Comment by J0WI** [comment]
Tag generation works for me:
```
$ ./generate-stackbrew-library.sh 
# This file is generated via https://github.com/phpmyadmin/docker/blob/7d35294fc583315159751950cd021127bf8ba5fe/generate-stackbrew-library.sh
Maintainers: Isaac Bennetch <bennetch@gmail.com>
             Michal Čihař <michal@cihar.com>
GitRepo: https://github.com/phpmyadmin/docker.git

Tags: 4.9.1-apache, 4.9-apache, 4-apache, 4.9.1, 4.9, 4
Architectures: amd64, arm32v7, arm64v8, i386, ppc64le
GitCommit: f522725291419d79945dec326dbd55b2bbc38186
Directory: apache

Tags: 4.9.1-fpm, 4.9-fpm, 4-fpm
Architectures: amd64, arm32v7, arm64v8, i386, ppc64le
GitCommit: f522725291419d79945dec326dbd55b2bbc38186
Directory: fpm

Tags: 4.9.1-fpm-alpine, 4.9-fpm-alpine, 4-fpm-alpine
Architectures: amd64, arm32v7, arm64v8, i386, ppc64le
GitCommit: f522725291419d79945dec326dbd55b2bbc38186
Directory: fpm-alpine
```
But one of the maintainers (@williamdes @ibennetch) still have to publish this to the library (#56).

**Comment by ibennetch** [comment]
Clearly I have missed a step somewhere; I’ll work on this later this evening.

**Comment by ibennetch** [comment]
Okay, I've investigated a bit. We don't currently generate tags for patch level releases, and AFAIK have never done so. So 4.9, edge, master, and latest are all appropriate tags, but 4.9.1 doesn't exist (and shouldn't, according to any of our documentation that I'm aware of). This is definitely the appropriate place to suggest making such changes in the future, though.

If I understand correctly, the `generate-stackbrew-library.sh` file is used by Docker hub, when we're able to get our package named as part of the official DockerHub list, but I'm still generating custom tags until then (which I admit has stalled a bit on my end).
