### ISSUE TITLE
4.9 image gives 502 bad gateway error when importing database.

### ISSUE THREAD

**Issue by shinebayar-g** [phpmyadmin/docker#233]
Just deployed new mysql and phpmyadmin using docker compose.

When I try to import sqldump file (under 1mb) into new database it gives back **502 bad gateway** error and I'm redirected to `/import.php`. (I'm using nginx reverse proxy in front of phpmyadmin).

If I browse back to phpmyadmin again, it just works normal like nothing happened. Database were imported (possible partially). No error logs in phpmyadmin container, and it's not crashed.

Looks like this bug introduced in `phpmyadmin/phpmyadmin:4.9`. Tested same steps in `4.8.5`, it's ok.

**Comment by williamdes** [comment]
Implemented in #261 :tada:

**Comment by matthuisman** [comment]
I still get this issue with latest phpmyadmin and a 300kb sql dump
