### ISSUE TITLE
can't seem to connect

### ISSUE THREAD

**Issue by Dorky106** [phpmyadmin/docker#236]
I'm using Community Applications in unraid to install my apps, no idea if this will make a difference a not figured I'd just toss it in there to be safe.
Using MySQL
For MySQL, just removed the underscores and put new in front of the user and passwords
For PMA, I changed the MySQL_Host to be the same as as the portmappings for mysql, and matched the user and password as the ones put into mysql

I get this
mysqli_real_connect(): The server requested authentication method unknown to the client [caching_sha2_password]
mysqli_real_connect(): (HY000/2054): The server requested authentication method unknown to the client

if my setup points the host to the same as PMA then I get a 
2002 connection refused

if my issue is more of a MySQL issue let me know and point me to where I should be asking for help.

**Comment by williamdes** [comment]
@Dorky106 you should have a look to https://github.com/phpmyadmin/phpmyadmin/issues/14220 and close this issue if it is solved by my linked issue :)
