### ISSUE TITLE
Increase max_upload_size

### ISSUE THREAD

**Issue by sajadghawami** [phpmyadmin/docker#237]
Hey guys,

i ve been searching for a few hours now how to change the `max_upload_size`, but it does not seem to work.
The size seems to have been changed in the last couple of weeks, because it was almost 512mb before.

I tried changind the sizes in `config.user.inc.php` like:

```
ini_set("upload_max_filesize", "1024M");
ini_set("post_max_size", "1024M");
ini_set("max_execution_time", "1000");
ini_set("max_input_time", "1000");
ini_set("max_input_vars", 10000);
```

But that did not seem to work.

Any help would be very appreciated!

**Comment by williamdes** [comment]
@J0WI could your changes have introduced this issue ?

**Comment by bobalazek** [comment]
Yes, but there's a workaround - I experienced the same issue a few minutes ago.

Just add the following to your `Dockerfile`:

```
RUN echo "file_uploads = On\n" \
         "memory_limit = 512M\n" \
         "upload_max_filesize = 512M\n" \
         "post_max_size = 512M\n" \
         "max_execution_time = 600\n" \
         > /usr/local/etc/php/conf.d/uploads.ini
```

**Comment by J0WI** [comment]
https://github.com/phpmyadmin/docker/pull/221

> `upload_max_filesize`/`post_max_size` are removed due docker-library/wordpress#10

**Comment by sajadghawami** [comment]
I found out that this has been changed in the base-image that is used for this one.

For anyone experiencing the same issue. You can do the following if you are using `docker-compose`:

```
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
````

Or with `docker run`:

```
docker run [other enviroments or configs] -v /php.ini:/usr/local/etc/php/conf.d/php.ini
```
