### ISSUE TITLE
Max upload size settings gone

### ISSUE THREAD

**Issue by shinebayar-g** [phpmyadmin/docker#240]
Looks like `4.9` version messed up again. `4.8` version had max upload size 512MiB. But `4.9` has `2,048KiB`. Also getting this 502 error everytime I import any database.

![image](https://user-images.githubusercontent.com/3091558/65896839-94caaa00-e3e0-11e9-8665-aa0e8a6f003e.png)
https://github.com/phpmyadmin/docker/issues/233

**Comment by williamdes** [comment]
@shinebayar-g Thanks for the report, a fix must be done.

**Comment by shinebayar-g** [comment]
![image](https://user-images.githubusercontent.com/3091558/71334232-3b55bf80-2578-11ea-981f-bbc50b15a25d.png)

You sure about that? Just downloaded newer 4.9 image and it's still same.

**Comment by williamdes** [comment]
As @J0WI said we should not change the value by should provide a ENV value to change it

**Comment by shinebayar-g** [comment]
@williamdes ah good point. ENV variables now ready to use or is it in progress?

**Comment by williamdes** [comment]
@shinebayar-g I would recommend that you subscribe to #261 where I will implement it

**Comment by williamdes** [comment]
Implemented in #261 :tada:
