### ISSUE TITLE
Phpmyadmin Docker configuration

### ISSUE THREAD

**Issue by stefanelul2000** [phpmyadmin/docker#243]
### Describe the bug

Can't edit config file.

### To Reproduce

Mounting /etc/phpmyadmin/ to a local directory and editing config.user.inc.php file makes phpmyadmin ignore the config parameters in the docker config.

### Expected behavior

After editing config.user.inc.php the ssl error should dissaper and I should be able to I frame phpmyadmin.

```php
$cfg['Servers'][$i]['ssl_verify'] = false;
$cfg['AllowThirdPartyFraming'] = true;
```

### Server configuration

- Operating system:Debian
- Web server:Apache
- Database version:10.3.18-MariaDB
- PHP version:7.2.22
- phpMyAdmin version:4.9.0.1

### Client configuration

- Browser: Chrome
- Operating system: Windows 10

**Comment by williamdes** [comment]
Your issue sounds similar to #181

**Comment by stefanelul2000** [comment]
I've manage to create the config.user.inc.php but if I edit $cfg['Servers'][$i]['ssl_verify'] = false; I am no longer able to access my server. the other config regarding iFraming works without any problems.

**Comment by williamdes** [comment]
#262 will help you when it is merged

**Comment by williamdes** [comment]
@stefanelul2000 #262 is now merged, you will be able to use the feature in the next release
