### ISSUE TITLE
Question: phpMyAdmin data storage

### ISSUE THREAD

**Issue by 3phreal** [phpmyadmin/docker#245]
I am fairly new to PHPMyAdmin. However I have an instance now up and running connecting to a MySQL server. I have configured PHPMyAdmin storage. 

My question is all the changes I do though phpMyAdmin where are they stored?. 

My MySQL DB is stored on a docker volume which can be ported however how do i port the settings from PHPMyAdmin ?

Regards

**Comment by williamdes** [comment]
> My question is all the changes I do though phpMyAdmin where are they stored?.

They are not stored, I think that if you enable tracking on some tables you can have a log of changes

> My MySQL DB is stored on a docker volume which can be ported however how do i port the settings from PHPMyAdmin ?

The settings move with the `phpmyadmin` database, expect for `config.inc.php` values

@lem9 Do you agree for the tracking feature ?

**Comment by 3phreal** [comment]
> > My question is all the changes I do though phpMyAdmin where are they stored?.
> 
> They are not stored, I think that if you enable tracking on some tables you can have a log of changes

What about new users and their privilages?

> 
> > My MySQL DB is stored on a docker volume which can be ported however how do i port the settings from PHPMyAdmin ?
> 
> The settings move with the `phpmyadmin` database, expect for `config.inc.php` values
> 

Where does this database reside. With my other SQL databases ?

> @lem9 Do you agree for the tracking feature ?

**Comment by williamdes** [comment]
> What about new users and their privilages?

> Where does this database reside. With my other SQL databases ?

All this data is in the `mysql` database and will move with the docker volume

**Comment by williamdes** [comment]
If this is still an issue pleas comment here :)
