### ISSUE TITLE
Please support arm

### ISSUE THREAD

**Issue by Demired** [phpmyadmin/docker#248]
arm
arm
arm

**Comment by Demired** [comment]
Is there anyone pushing the work forward?

If not, leave it to me. I already use it on arm.

**Comment by williamdes** [comment]
@Demired I refactored the Travis CI file in https://github.com/phpmyadmin/docker/commit/9d1872d75350bf65e5bbb4530e3df5e86511b52c and you can now easily add arm64
But CI fails
If you want to fix it go ahead

**Comment by J0WI** [comment]
See also #56 for `arm32v5`, `arm32v6`, `arm32v7`, `arm64v8`, `i386` and `ppc64le`.

**Comment by mzac** [comment]
Good example here to use multi-arch.  

https://github.com/marketplace/actions/docker-buildx

**Comment by williamdes** [comment]
Thank you !
If someone can do a pull-request this would be super helpful :)
I think this well be solved by #56 and https://github.com/docker-library/official-images/pull/7288

**Comment by TrAnn3l** [comment]
This is obsolete with https://hub.docker.com/_/phpmyadmin
