### ISSUE TITLE
[Question] Should config file be mounted as ro or rw?

### ISSUE THREAD

**Issue by lonix1** [phpmyadmin/docker#254]
I'm mounting a config file like this:
````
- ./config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:ro
````

It's customary to mount config files as readonly (`ro`).

But when I run it, I get this in the log:

````log
phpmyadmin_1  | touch: /etc/phpmyadmin/config.user.inc.php: Read-only file system
````

Why is the config file touched / edited? Is it safe to keep it `ro`, or must I change it to `rw`?

**Comment by ibennetch** [comment]
I don't know why this is being touched; in the Dockerfile we test if it exists, and if it doesn't, we create it with touch.

I think this is left over code from a long time ago. It was first introduced in 4cadf08f, and there was no error checking in the "include" statement in config.inc.php to test whether or not the config.user.inc.php file exists. I suspect the author touched the file to make sure it exists, so as to not perform a test if the file exists.

Now, we do test for that file in config.inc.php, so I'm pretty sure the touch block could be removed.

**Comment by williamdes** [comment]
https://github.com/phpmyadmin/docker/blob/7d8a3e5717fd3160a74ce9bb2a28bc7444481347/docker-entrypoint.sh#L45-L47

**Comment by williamdes** [comment]
`touch: setting times of '/etc/phpmyadmin/config.user.inc.php': Read-only file system`

**Comment by williamdes** [comment]
@lonix1 I had the issue you reported when mounting a fie that does not exist

**Comment by lonix1** [comment]
Glad it was not just me 😄
