### ISSUE TITLE
[Feature Request] Environment variable INSTALL_DIRECTORY

### ISSUE THREAD

**Issue by lonix1** [phpmyadmin/docker#255]
The [`docker-entrypoint.sh`](https://github.com/phpmyadmin/docker/blob/master/docker-entrypoint.sh#L22) installs by default into `/var/www/html/` (determined by `$PWD`).

This makes docker config more complicated. For example when using nginx to serve multiple apps, we need to use `/var/www/phpmyadmin` instead. There are workarounds, but it's messy.

Please add a new environment variable, e.g. `INSTALL_DIRECTORY`. If it is set then use it instead of `$PWD`, otherwise just use `$PWD` as normal.

**Comment by lonix1** [comment]
The workaround I'm using:
- in phpmyadmin container, I map `phpmyadmin_data:/var/www/html/`
- in nginx container, I map `phpmyadmin_data:/var/www/phpmyadmin/`

**Comment by williamdes** [comment]
Related to #230

**Comment by williamdes** [comment]
@J0WI can I ask you some advice on how to implement such a directory change without having to a 3K lines of configuration ?
apache2-foreground seems to want configuration, I was thinking about a symlink

**Comment by J0WI** [comment]
It's not necessary to change the `INSTALL_DIRECTORY`.
@lonix1 what is your nginx configuration? You can also change `alias`, `root` or `fastcgi_param  DOCUMENT_ROOT` to serve multiple apps.

**Comment by lonix1** [comment]
Yes but then other apps cannot use `/var/www/html/`. In the nginx container only one app can live there.

**Comment by J0WI** [comment]
You can use whatever directory you prefer for nginx. https://github.com/phpmyadmin/docker/issues/255#issuecomment-545033475 is rather a common practice than a workaround.

**Comment by lonix1** [comment]
Ok
