### ISSUE TITLE
Missing docker tags of micro version

### ISSUE THREAD

**Issue by johan-smits** [phpmyadmin/docker#256]
### To Reproduce

1. Go to https://hub.docker.com/r/phpmyadmin/phpmyadmin/tags
2. See that since `4.8.5` there is only a `4.9` tag. No `4.9.2` available.

### Expected behavior

Have also the micro versions in the tags.

**Comment by williamdes** [comment]
@johan-smits `docker pull phpmyadmin/phpmyadmin:4.9.2-1` or `docker pull phpmyadmin/phpmyadmin:4.9.1`
We fixed that now, thank you for reporting

**Comment by ibennetch** [comment]
This should now be resolved, fixed by #259

**Comment by deeky666** [comment]
@ibennetch this is happening again for the latest `5.0` release.

**Comment by ibennetch** [comment]
Indeed, I was tweaking the Docker Hub build rules relating to the changes for #259 and think I missed something. I'll work on it now...

**Comment by ibennetch** [comment]
This should be fixed now. I goofed a bit with the build rules and have resolved that problem. Since I'm adjusting a lot of the rules, please feel free to let me know if you see anything else amiss.

**Comment by deeky666** [comment]
@ibennetch thank you very much!
