### ISSUE TITLE
PMA_HOSTS_FILE in GKE do not work?

### ISSUE THREAD

**Issue by eriksenonline** [phpmyadmin/docker#260]
In the documentation, it says we can use _FILE for all variables

> PMA_PASSWORD_FILE=/run/secrets/db_password.txt

I tested this on Kubernetes using PMA_HOSTS_FILE and for some reason, the variables are not read into the configuration. I also tested with PMA_HOST_FILE, this did not work either.

When I test using normal env variables it works but when I try to read from a file it does not work. I did a cat of the file inside the container and the content was mounted. The content of the mounted PMA_HOSTS_FILE is 10.x.x.x, 10.x.x.x only. Nothing else.

Is the docker image not supporting the _FILE for all variables or am I doing something wrong?

**Comment by williamdes** [comment]
Hi

As said in #247 the documentation is wrong and should be fixed by #247  
Maybe you can ask on #247 to implement hosts :)

**Comment by eriksenonline** [comment]
Thanks for that I asked on #247
