### ISSUE TITLE
4.9.3 version missing

### ISSUE THREAD

**Issue by shinebayar-g** [phpmyadmin/docker#266]
There isn't `4.9.3` tag available and `4.9` is coming with 4.9.2 version.

**Comment by ibennetch** [comment]
Thank you for reporting this. I've pushed a change and triggered a rebuild,
which will take a while. I'll check on it again in tomorrow and report back
here what I find.

**Comment by shinebayar-g** [comment]
Thanks

**Comment by ibennetch** [comment]
This is resolved now, there's a 4.9.3 tag now and it's pulling the correct version for me.

I changed a lot of the build rules as part of the changes for #259, so please let me know if you see anything else amiss.
