### ISSUE TITLE
Container shuts down when enabling SSL module in Apache (for HTTPS)

### ISSUE THREAD

**Issue by salvador-moreno** [phpmyadmin/docker#269]
I want to access the Phpmyadmin container over HTTPS through the port 443. However, when I enable SSL module for Apache and restart the service, the container automatically shuts down with signal Exit 0, and every time I try to start it again, returns Exit 1.

Any ideas on why this is happening? I have seen that openssl is installed in the container.

**Comment by williamdes** [comment]
@salvador-moreno can you post your command line or docker-compose file ?

**Comment by salvador-moreno** [comment]
Inside the running container, instead of restarting the service (`service apache2 restart`), just reloading the configuration does the job and doesn't kill the container (`service apache2 reload`).

Furthermore, the apache ssl module can be enabled within the Dockerfile before creating the container that there is no need for restart/reload (`RUN a2enmod ssl`).
