### ISSUE TITLE
Add Kubernetes support

### ISSUE THREAD

**Issue by kop** [phpmyadmin/docker#27]
It is currently not possible to use this image with Kubernetes because of known bug in `alpine` image.
It would be great to have an additional tag, suffixed with `-k8s`, that will use [janeczku/alpine-kubernetes](https://hub.docker.com/r/janeczku/alpine-kubernetes/) as a base image.

**Comment by nijel** [comment]
Reading what it does, it might fix https://github.com/phpmyadmin/docker/issues/23 as well...

**Comment by nijel** [comment]
Also it seems to be fixed in alpine as well: https://twitter.com/thockin/status/704909611279781888
