### ISSUE TITLE
Add ability to connect via MySQL socket instead of TCP

### ISSUE THREAD

**Issue by kop** [phpmyadmin/docker#28]
In some setups, MySQL is not available via TCP and only listens via socket. It would be great to have an ability to set MySQL socket instead of hostname.

**Comment by nijel** [comment]
You mean running MySQL in same docker container like phpMyAdmin? I don't think sockets can work across containers....

**Comment by nijel** [comment]
It's not possible to share sockets, see http://serverfault.com/a/588720/28295. And I really don't see point in running MySQL inside phpMyAdmin container listening on socket.
