### ISSUE TITLE
Possible "PMA_USER_CONFIG_BASE64" (NavigationTreeEnableGrouping) bug

### ISSUE THREAD

**Issue by firecow** [phpmyadmin/docker#280]
![image](https://user-images.githubusercontent.com/973602/77680306-0fd9db00-6f94-11ea-8f27-622d6030a2e7.png)
![image](https://user-images.githubusercontent.com/973602/77680362-22ecab00-6f94-11ea-9056-c0db2f0ceaa8.png)
![image](https://user-images.githubusercontent.com/973602/77680582-77902600-6f94-11ea-9c29-0bd4c308f130.png)

I'm trying to use PMA_USER_CONFIG_BASE64 to keep my databases from folding on "_".
I can't seem to figure out what I'm doing wrong.
Perhaps I found a bug ?

**Comment by williamdes** [comment]
Could you please post the config block as Plein text si I can test it locally?

**Comment by firecow** [comment]
```PMA_USER_CONFIG_BASE64: "JGNmZ1snTmF2aWdhdGlvblRyZWVFbmFibGVHcm91cGluZyddID0gZmFsc2U7Cg=="```

**Comment by williamdes** [comment]
@firecow please try `echo '<?php $cfg['NavigationTreeEnableGrouping'] = false;' |base64`
`PD9waHAgJGNmZ1tOYXZpZ2F0aW9uVHJlZUVuYWJsZUdyb3VwaW5nXSA9IGZhbHNlOwo=`

**Comment by firecow** [comment]
Oh... Ofcourse its a php file. My bad.
Works like a charm. Thanks. :smile:

**Comment by williamdes** [comment]
:tada:
