### ISSUE TITLE
Docker PHPmyadmin Access?

### ISSUE THREAD

**Issue by brandontamm** [phpmyadmin/docker#30]
I've got a project that sets phpmyadmin up in docker-compose using the following configuration:

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: "mysql"
      PMA_PORT: 3306

I need to import sql but I'm not sure how to access either via command line, browser, or sequel pro (where do I find the credentials to use?)
ssh host-?
ssh user-?
ssh key-?

Preferably sql pro so I can view all the data and learn the structure better :)

**Comment by nijel** [comment]
You can access it by web. If you want direct access to the database, rather check the mysql container...
