### ISSUE TITLE
changing port number and where to find compose.yml file

### ISSUE THREAD

**Issue by MhmdSuleiman** [phpmyadmin/docker#306]
Greeting
i want to change port number for my running container.so how can change it?
 i want to know where can i found docker-compose.yml file if it's exist?
note that my docker image from "Usage with linked server"

**Comment by williamdes** [comment]
Hi
I think this is a duplicate of https://github.com/phpmyadmin/docker/issues/138
Maybe https://github.com/phpmyadmin/docker/issues/138#issuecomment-599023714 would solve your issue
