### ISSUE TITLE
Vulnerabilities

### ISSUE THREAD

**Issue by jose-joaquin** [phpmyadmin/docker#308]
![image](https://user-images.githubusercontent.com/39832733/95328149-216d3b00-0873-11eb-9000-aa2ae9144a9f.png)

**Comment by ibennetch** [comment]
Thanks for the report. I think this doesn't really affect us because we don't mount other file systems and don't use btrfs at all, but I've triggered the current builds to rebuild anyway. They should finish within another half hour or so.
