### ISSUE TITLE
Build on docker hub is failing

### ISSUE THREAD

**Issue by titpetric** [phpmyadmin/docker#31]
https://hub.docker.com/r/phpmyadmin/phpmyadmin/builds/

**Comment by nijel** [comment]
It's probably due to some alpine edge error. We have to use edge version due to several problems in 3.3 (see #23, #27, 6dd6b90902e4a124ce20e93f3b456f23b30855d1, 249e10deccb76e282eda0271ef17a7bd8c47696a).

**Comment by nijel** [comment]
See also http://bugs.alpinelinux.org/issues/5601

**Comment by titpetric** [comment]
Consider making separate builds against debian/jessie or others. I'm fine with using tags for specific versions against different source images. I could submit a PR next week if you'd like.

**Comment by nijel** [comment]
We originally based on debian, but the image size is really big with it...

**Comment by nijel** [comment]
Anyway it seems they have just renamed php packages in alpine, I'm trying to rebuild it now...

**Comment by nijel** [comment]
Okay, that was all what was needed, fixed in 15ca16c.
