### ISSUE TITLE
how about support /etc/phpmyadmin/conf.d ?

### ISSUE THREAD

**Issue by pigochu** [phpmyadmin/docker#319]
As title

I don't want modify config.user.inc.php

If I  create a custom phpmyadmin image for my team members ,  Other member can define custom config in config.user.inc.php.
But this image need load other special config .
So I hope it can support /etc/phpmyadmin/conf.d , let us put config.

**Comment by williamdes** [comment]
Hi @pigochu 
I am in favor of this option as it already exists on the Debian package: https://salsa.debian.org/phpmyadmin-team/phpmyadmin/-/blob/debian/4%255.1.1+dfsg1-2/debian/conf/config.inc.php#L159

@J0WI any opinions about this ?

**Comment by LeeThompson** [comment]
This would be great!

**Comment by pigochu** [comment]
Can this function be implemented? Because I found that when I mount config.user.inc.php on the host as a volume, when I use vim to edit config.user.inc.php, then the container will find The name and attributes of the file become a bunch of question marks, and if you want to view the file in the container, there will be a stale file halder error. I think using conf.d can avoid this problem.

**Comment by williamdes** [comment]
> Can this function be implemented? Because I found that when I mount config.user.inc.php on the host as a volume, when I use vim to edit config.user.inc.php, then the container will find The name and attributes of the file become a bunch of question marks, and if you want to view the file in the container, there will be a stale file handle error. I think using conf.d can avoid this problem.

For sure, I would like to have it too.
You can send a PR for it before someone has the chance to do it
This file is probably the one that should be edited: https://github.com/phpmyadmin/docker/blob/0006406e352ddd5addd5122de53fe354307b2460/config.inc.php#L159-L161

**Comment by williamdes** [comment]
Done in #401
