### ISSUE TITLE
controlpass in file

### ISSUE THREAD

**Issue by niclem** [phpmyadmin/docker#321]
Hi, could you configure docker image to permit passing PMA_CONTROLPASS variable in file like it's possible with other sensitive variables ?

    PMA_PASSWORD
    MYSQL_ROOT_PASSWORD
    MYSQL_PASSWORD
    PMA_HOSTS
    PMA_HOST

Thanks !
Nicolas

**Comment by williamdes** [comment]
Sure, I see no good reason not to allow that :)

**Comment by niclem** [comment]
Ok ok I understood ;)
