### ISSUE TITLE
Error TemDir in 5.1 image

### ISSUE THREAD

**Issue by JeremieMercier** [phpmyadmin/docker#330]
Hi,

After installing phpmyadmin image:latest

I have an error: 
`$cfg['TempDir'] (/var/www/html/tmp/)`

I think this is the same mistake you had already corrected on issue #156 ?

**Comment by williamdes** [comment]
I did a quick search and the folder is the right one, I am checking if I can reproduce this issue
https://github.com/phpmyadmin/docker/blob/4482d47ca7f5093121ad634fc6e21865dcf03ffb/apache/Dockerfile#L108

**Comment by williamdes** [comment]
Bonjour @JeremieMercier 
Could you pull the latest official image and let me know if the issue is still there ?
If yes could you provide me your docker configuration ?

**Comment by JeremieMercier** [comment]
I confirm I no longer have the problem, sorry for not having answered earlier
