### ISSUE TITLE
Run mysql inside the phpmyadmin container just for the storage purpose?

### ISSUE THREAD

**Issue by Mike-the-one** [phpmyadmin/docker#332]
I want to use phpmyadmin with 2FA to manage my databases, however, I don't want phpmyadmin to store anything on my product mysql server.  I am wondering if I can setup a phpmyadmin container, it also has an embedded mysql running, so that I can config phpmyadmin to use the embedded mysql for storage only?

Thanks

**Comment by williamdes** [comment]
Hi @Mike-the-one 
You need to use `PMA_CONTROLHOST` to use another control host to host the phpMyAdmin storage database
(https://github.com/phpmyadmin/docker#environment-variables-summary)
