### ISSUE TITLE
Getting error on pull

### ISSUE THREAD

**Issue by Nv7-GitHub** [phpmyadmin/docker#335]
When I use `docker run`, I get the error:
```
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.
```
Any ideas on how to fix this?

**Comment by williamdes** [comment]
Hi !
As phpMyAdmin we can not do much, but I would recommend you to re-try and check if you need or have a proxy configured.

Also, be sure to use the official image: `phpmyadmin` (`docker pull phpmyadmin:latest`)

**Comment by Nv7-GitHub** [comment]
I managed to fix this issue.

**Comment by ibennetch** [comment]
@Nv7-GitHub how did you solve it?
