### ISSUE TITLE
How to add to apache.conf?

### ISSUE THREAD

**Issue by Nv7-GitHub** [phpmyadmin/docker#337]
Right now in phpMyAdmin status monitor I do not see CPU usage, memory usage, or swap usage. I read at https://infraadvisory.wordpress.com/2015/07/23/cpu-memory-stats-in-phpmyadmin/comment-page-1/ that adding a specific line to `apache.conf` would make these show up. How do I add to `apache.conf` with this Docker image?

**Comment by williamdes** [comment]
This tutorial seems like a very old hack for the Debian packaging system
Maybe you can try to add a column to the graph to add CPU usage
Maybe this is related to the CPU arch you use?

**Comment by Nv7-GitHub** [comment]
How do i add a column to the graph?

**Comment by williamdes** [comment]
> How do I add a column to the graph?

![image](https://user-images.githubusercontent.com/7784660/125146221-09d62200-e125-11eb-87b4-575587061ed4.png)


Like this, let me know if it works as expected

**Comment by Nv7-GitHub** [comment]
All that did was make the columns smaller

**Comment by williamdes** [comment]
Can you post a screenshot please ?

**Comment by Nv7-GitHub** [comment]
Never mind, I had made chart columns to 6, adding new charts worked. Sorry!

**Comment by williamdes** [comment]
> Never mind, I had made chart columns to 6, adding new charts worked. Sorry!

No worries, feel free to open a new issue if you find a bug
