### ISSUE TITLE
config.user.inc.php is ignored when running phpMyAdmin in Docker

### ISSUE THREAD

**Issue by pcgeek86** [phpmyadmin/docker#338]
## Synopsis

I am trying to modify a configuration file inside of a container running phpMyAdmin, using the official container image. I am **not** bind mounting a configuration file into the container. Instead, I am installing vim into the container, and manually modifying the configuration file. 

If I modify `/etc/phpmyadmin/config.inc.php`, then the configuration changes take effect immediately, without having to restart the container. However, when I modify `/etc/phpmyadmin/config.user.inc.php`, the changes do not take effect.

## Reproduction Steps

1. Spin up a new container `docker run -d -e PMA_ARBITRARY=1 --env UPLOAD_LIMIT=40M -p 50005:80 phpmyadmin`
1. Exec into the container `docker exec -it <containerID> bash`
1. Install vim `apt update && apt install vim --yes`
1. Use vim to edit the config file `vim /etc/phpmyadmin/config.user.inc.php`
1. Add a configuration line, for example `$cfg['ShowServerInfo'] = false;`
2. Save / quit vim, and go to the phpMyAdmin home page. 
3. Observe that the server information still appears, despite the configuration setting

If you place the configuration setting into `config.inc.php`, however, then it works as expected.

**Comment by williamdes** [comment]
Hi @pcgeek86

Did you add a first line `<?php` before your config line?

**Comment by pcgeek86** [comment]
Thanks for pointing out my error! I didn't realize I needed to do that. I don't write PHP, hence I'm clueless about how it works.

**Comment by williamdes** [comment]
> Thanks for pointing out my error! I didn't realize I needed to do that. I don't write PHP, hence I'm clueless about how it works.

No worries, as you can put any content you want in php files and merge php code into the content you need to open php tags and also maybe close them 

Glad this helped you, you would probably want to use a file bind like a volume to avoid having to do changes in the container
