### ISSUE TITLE
Any reason not to update this to use PHP 7?

### ISSUE THREAD

**Issue by ssteinerx** [phpmyadmin/docker#34]
I'm using PHP 7 everywhere now and am curious if there's a reason not to update this package.

Thanks,

S

**Comment by nijel** [comment]
Last time I checked PHP 7 was not included in alpine linux, that's why there is php 5 still :-)

**Comment by nijel** [comment]
Okay, it's still not there, it's just in edge and I don't think it's worth using edge because of this...

**Comment by ssteinerx** [comment]
Agreed, let's just wait for 3.5, then for this image.  I'll fold it into my php7 for the moment, no real need for a separate image with a duplicate PHP setup.

**Comment by CybotTM** [comment]
why not using php alpine image?

php:alpine or php:7-alpine

**Comment by ssteinerx** [comment]
@CybotTM -- as of last check PHP 7 was not yet available (alpine 3.4).  Is it now?

**Comment by CybotTM** [comment]
@ssteinerx i do not understand the intention of your question ... php:7-alpine ist PHP Version 7 on alpine

i do not know if there is a PHP 7 package by alpine itself - but why does this matter?

**Comment by ssteinerx** [comment]
@CybotTM -- my understanding, from the discussion above, is that the maintainer wants to use the official Alpine package repository.  Not my project, not my decision.

**Comment by ssteinerx** [comment]
I agree with @CybotTM -- no reason not to use php7-alpine from here:

https://hub.docker.com/_/php/

It may not be an official Alpine release, but it's an official PHP7 release.

**Comment by nijel** [comment]
Actually we would need fpm-alpine, but certainly that's an option. From quick look it lacks some extensions we use, but that seems to be solvable.

**Comment by ssteinerx** [comment]
@CybotTM I don't have time for this right now, but if you're familiar with that image and wanted to take a shot at a patch, I'd be happy to test and confirm it works to endorse a pull request.

**Comment by CybotTM** [comment]
I will have a look into it.
