### ISSUE TITLE
[question] Why is the composer.json file removed from the image?

### ISSUE THREAD

**Issue by RubenAtPA** [phpmyadmin/docker#345]
When trying to add a custom authentication plugin we need to be able to add some composer packages. Now I noticed that the composer.json file is purposely removed from the image. This leaves the question: why? This makes it extra difficult to do some custom changes to this image.

**Comment by williamdes** [comment]
Yes it seems removed, I am not sure why
https://github.com/phpmyadmin/docker/blob/master/Dockerfile-debian.template#L111

I found it was done in 50f822a1c96f13abb3e645172948a615a7148120 to fix #78

Anyway, I will revert for composer.json and adjust the line.
cc @emanuelb

**Comment by RubenAtPA** [comment]
@williamdes Thanks for picking it up so quickly. Any idea when this change will be pushed in a new image at dockerhub?

**Comment by williamdes** [comment]
> @williamdes Thanks for picking it up so quickly. Any idea when this change will be pushed in a new image at dockerhub?

Most probably on next phpMyAdmin release
Maybe in a big bunch of days
You can subscribe to releases on this page after the 🌟 star button ;)
