### ISSUE TITLE
Mutli platform support

### ISSUE THREAD

**Issue by trickert76** [phpmyadmin/docker#348]
Would it be possible to build and push a multi platform image to docker automatically. I've testet that with my own images and it's easy as expected. The base images for PHP are alread available for arm64 und amd64, etc. So why not using it.

The documentation on https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md is very straightforward and is everything that is necessary to push the image the latest versions after a sucessful ci run.

I'm not sure - the Makefile is as easy to. Then we need a special docker container in github actions with buildx-bin cli extension. There are also a lot of examples in the web, like:

```
docker buildx create --driver docker-container --use
docker buildx build \
  --platform linux/arm64,linux/amd64 \
  --pull \
  --tag ${ARTIFACT_TAG} \
  --push \
  ./
```

**Comment by williamdes** [comment]
There is a multi platform image ;)
Here it is: https://hub.docker.com/_/phpmyadmin

**Comment by trickert76** [comment]
Aaaah, that is awkward. I looked into my Docker Desktop and it shows me an AMD64 image on a M1. I'm using docker-compose and the image `phpmyadmin/phpmyadmin`. Don't know, where I found that image. But switching to `phpmyadmin` helped... sorry for the noise...

**Comment by williamdes** [comment]
> Aaaah, that is awkward. I looked into my Docker Desktop and it shows me an AMD64 image on a M1. I'm using docker-compose and the image `phpmyadmin/phpmyadmin`. Don't know, where I found that image. But switching to `phpmyadmin` helped... sorry for the noise...

No worries, this was the old image that was in use before we applied for an official image.
Happy that it worked for you

Have a nice day
