### ISSUE TITLE
Update php in docker to 8.0.12/13?

### ISSUE THREAD

**Issue by Kaczuc** [phpmyadmin/docker#349]
When can you expect php update in the docker image to version 8 I'm using lastet image for arm64 host machine

**Comment by ibennetch** [comment]
The next phpMyAdmin release will migrate to PHP 8; see also #325.

**Comment by ibennetch** [comment]
The latest Docker images use PHP 8.0 (starting with release 5.1.2, although 5.1.3 has just been published). See also 7c28533a32a4a1bc4b932ac741e0334d7511e82e.

Thank you
