### ISSUE TITLE
phpmyadmin 5.1.2 docker image not yet available from docker.io registry

### ISSUE THREAD

**Issue by grunlab** [phpmyadmin/docker#352]
phpmyadmin 5.1.2 has been released 3 days ago but is not yet available from docker.io registry: https://hub.docker.com/_/phpmyadmin?tab=tags&page=1&name=5.1.2

Could you please make it available ?
Thank you

**Comment by paolobarbolini** [comment]
https://github.com/docker-library/official-images/pull/11723#issuecomment-1019303647

**Comment by grunlab** [comment]
Any update regarding phpmyadmin 5.1.2 or 5.1.3 availability on dockerhub ?
Thank you.

**Comment by williamdes** [comment]
Hi,
We are working on some last fixes before releasing 5.1.3, that should be very soon

**Comment by ibennetch** [comment]
phpMyAdmin 5.1.3 has been published.

Thank you.
