### ISSUE TITLE
centos 7.3 cannot run phpmyadmin docker

### ISSUE THREAD

**Issue by lan2720** [phpmyadmin/docker#355]
![image](https://user-images.githubusercontent.com/5330101/157254858-cb3ae7bf-147e-4498-bd45-e62bed0a4038.png)

centos 7.3, linux kernel: `3.10.0-514.21.1`
cannot run phpmyadmin:latest. It raised such an error:
![image](https://user-images.githubusercontent.com/5330101/157255594-70112b18-91f4-46d7-b56f-443e1c814042.png)

But centos 7.6 is ok, which linux kernel is `3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

Anyone know how to run phpmyadmin in centos 7.3 machine?

**Comment by williamdes** [comment]
Hi @lan2720 
Are you using the phpMyAdmin image from the official docker repository ?
Can you share your command line or yaml config ?

I am afraid this is out of the scope of what in our control about docker images, but let's find out

**Comment by qeepcologne** [comment]
i think it is caused by libapr1, you can try to downgrade it?
function was introducted in kernel 3.17, don't know how it works at all in 3.10 kernel of centos7.x (maybe backport)?
in general i can't image any reason to use or support eol centos (below 7.9).

**Comment by williamdes** [comment]
> i think it is caused by libapr1, you can try to downgrade it? getrandom interface was added in kernel 3.17, don't know how it works at all in 3.10 kernel of centos7.x (maybe backport)? in general i can't image any reason to use or support eol centos (below 7.9).

We can not change much of the base PHP image because we use the official PHP image as a base image
Did you find a workaround or fix since then ?
