### ISSUE TITLE
[docker hub] update apache version in latest phpmyadmin docker hub image

### ISSUE THREAD

**Issue by Ahmed-Galal** [phpmyadmin/docker#358]
- Is there any way to update the apache version in the latest image of PHPMyAdmin (in docker hub) from apache v =2.4.51 to apache v=2.4.53 because that appears as a vulnerability in the security scan.

**Comment by williamdes** [comment]
Hi @Ahmed-Galal
Nope, you need to open an issue on the php image because we do not install apache
To report: https://github.com/docker-library/php/issues 
See: https://github.com/phpmyadmin/docker/blob/026ddf5c119df6e87abd5ea19976b3baa3d8ed81/apache/Dockerfile#L1

**Comment by williamdes** [comment]
```sh
docker pull php:8.0-apache
docker run --rm php:8.0-apache
```
It outputs `Apache/2.4.53 (Debian) PHP/8.0.17`

That said
```sh
docker pull phpmyadmin:apache
```
Also outputs `Apache/2.4.53 (Debian) PHP/8.0.17` so your request is already done ;)

**Comment by Ahmed-Galal** [comment]
Thanks, @williamdes 
I just change the image to `image: phpmyadmin:apache` in my `docker-compose.yml` and it works
