### ISSUE TITLE
config.user.php and config.user.inc.php ignored

### ISSUE THREAD

**Issue by nunoperalta** [phpmyadmin/docker#364]
Trying to install phpMyAdmin in a new docker-compose set here, but I don't seem to be able to get it working the way I want.

I have:

```yml
    volumes:
      - ./config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
```

But everything there seems to be ignored.
Even if I put an `exit;` at the top. The login page loads.

Even if I put:

```yml
    volumes:
      - ./config.user.php:/etc/phpmyadmin/config.user.php
```

with an `exit;` at the top, the login page still loads.

If I open shell inside the container, I can verify that the files are there for sure.
But phpMyAdmin seems to be ignoring those configs completely!

Using the `:latest` version...

File starts with:

```php
<?php
exit;
```

---

I deleted the container, and put:

```yml
    environment:
      - PMA_ARBITRARY=1
    #volumes:
    #  - ./config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
```

To see if I make it show the Server field... nope!
Still the default page.
Not really sure what's going on!

**Comment by nunoperalta** [comment]
Tag `phpmyadmin:5.1.0` works...

**Comment by williamdes** [comment]
> Tag `phpmyadmin:5.1.2` works...

5.1.3 should work too

**Comment by williamdes** [comment]
Related to #361

**Comment by nunoperalta** [comment]
> > Tag `phpmyadmin:5.1.2` works...
> 
> 5.1.3 should work too

oh... yesterday when I was downloading `:latest`, the Docker page at https://hub.docker.com/_/phpmyadmin was saying that the latest version was 5.1.3.

Now I see it says 5.2.0.
So, are you saying this is a new bug in 5.2.0, and that I was actually downloading that version? 🤦‍♂️ 😅

That explains then.
Because, I have another instance running for months with 5.1.3 and it works fine!

**Comment by williamdes** [comment]
> > > Tag `phpmyadmin:5.1.2` works...
> > 
> > 
> > 5.1.3 should work too
> 
> oh... yesterday when I was downloading `:latest`, the Docker page at https://hub.docker.com/_/phpmyadmin was saying that the latest version was 5.1.3.
> 
> Now I see it says 5.2.0. So, are you saying this is a new bug in 5.2.0, and that I was actually downloading that version? man_facepalming sweat_smile
> 
> That explains then. Because, I have another instance running for months with 5.1.3 and it works fine!

For 5.2.0 I have no idea this error comes from since we changed nothing on the Dockerfiles between 5.1.3 and 5.2.0

@tianon Did you say there is a Debian update in progress ?

**Comment by Slamdunk** [comment]
I can confirm this issue: starting from `5.2.0`, the file `/etc/phpmyadmin/config.user.inc.php` gets now ignored.

Until `5.1.3` it used to be read as expected.

**Comment by pjbakker** [comment]
Had the same issue.

The latest version is **NOT** reading */etc/phpmyadmin/config.inc.php*, but */var/www/html/config.inc.php* and there is no symlink present. Making the symlink solves the problem..

**Comment by ibennetch** [comment]
A fix for this has been submitted to the official Docker repository.

Our own 'phpmyadmin/phpmyadmin' repository has already been updated, but as I mention in #363 I hope to deprecate that repository in the future.

**Comment by nunoperalta** [comment]
> Our own 'phpmyadmin/phpmyadmin' repository has already been updated,

Thanks for that. But what about the official image? `phpmyadmin`
That seems to be outdated still.
Thanks!

**Comment by williamdes** [comment]
> > Our own 'phpmyadmin/phpmyadmin' repository has already been updated,
> 
> Thanks for that. But what about the official image? `phpmyadmin` That seems to be outdated still. Thanks!

Pending review ;)
See: https://github.com/docker-library/official-images/pull/12425
