### ISSUE TITLE
PMA_ARBITRARY broken in latest version

### ISSUE THREAD

**Issue by florisvdk** [phpmyadmin/docker#366]
Setting PMA_ARBITRARY:1 does not work in the latest version, going back to 5.1.3 works with the exact same config otherwise.

**Comment by m-schmailzl** [comment]
I am experiencing the same issue. In the latest version (5.2.0-apache) the PMA_ARBITRARY setting has no effect.

**Comment by williamdes** [comment]
See #361 
I pushed a fix to fix the image build process, and expect this to be live as soon as possible when images are re built

**Comment by ibennetch** [comment]
A fix for this has been submitted to the official Docker repository.

Our own 'phpmyadmin/phpmyadmin' repository has already been updated, but as I mention in #363 I hope to deprecate that repository in the future.
