### ISSUE TITLE
Add Themes

### ISSUE THREAD

**Issue by pyros2097** [phpmyadmin/docker#37]
How do you add themes to this image? Is the best possible way to create my own image from this or would it be good to have all the themes preloaded with this image? I don't know if it will take too much space though?

**Comment by nijel** [comment]
I'm not really sure if increasing size of the image is the way to go...

**Comment by pyros2097** [comment]
What I saw was the image size is going to increase about 26mb if you add all the themes will that be an issue right now its 56mb

**Comment by pyros2097** [comment]
I guess it doesn't matter now.. Most of those themes are outdated and only the metro theme seems good so I made my owm image with that theme...

**Comment by nijel** [comment]
Indeed it is the only up to date theme right now. I think it's better to keep Docker image close to upstream in this. Maybe it's better to decide which themes to ship with phpMyAdmin 4.7, I've created issue for that: https://github.com/phpmyadmin/phpmyadmin/issues/12373

**Comment by devmarcelosantos** [comment]
Hello, how do I add themes to the phpmyadmin image? I can not find the phpmyadmin folder in ubuntu and the docker-compose -it CONTAINER bash command does not work either.
Sorry for the ignorance, I'm new to this.
The name of my container is phpmyadmin.php4devs. If you can help me, thank you very much!

**Comment by nijel** [comment]
Seems this deserves at least some documentation...
