### ISSUE TITLE
Function not implemented: AH00141: Could not initialize random number generator

### ISSUE THREAD

**Issue by 201206030** [phpmyadmin/docker#373]
The problem occurs when I install the latest version(5.2.0) of phpmyadmin using docker.

**Install Command**

    $ docker run --name myadmin -d -e PMA_HOST=dbhost -p 8080:80 phpmyadmin

**Docker Info**

    Server Version: 20.10.17 
    Kernel Version: 3.10.0-514.26.2.el7.x86_64 
    Operating System: CentOS Linux 7 (Core) 
    OSType: linux 
    Architecture: x86_64

If I change the version of phpmyadmin to 4.9.6 there will be no problem. 

----------
**Docker Info**

    Server Version: 19.03.8 
    Kernel Version: 3.10.0-957.21.3.el7.x86_64
    Operating System: CentOS Linux 7 (Core) 
    OSType: linux 
    Architecture:x86_64

There is no problem installing the latest version on the above environment.I don't know if it is because the Kernel version is too low, but the Kernel version is not allowed to be modified. Is there any other solution?

**Comment by 201206030** [comment]
If I change the version of phpmyadmin to 4.9.6 there will be no problem

**Comment by 201206030** [comment]
Docker Info:
 Server Version: 19.03.8
 Kernel Version: 3.10.0-957.21.3.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64

There is no problem installing the latest version on the above environment.I don't know if it is because the Kernel version is too low, but the Kernel version is not allowed to be modified. Is there any other solution?

**Comment by williamdes** [comment]
Hi!
Unfortunately this is way out of the scope of the phpMyAdmin image but I found some similar issues on  GitHub:
- https://github.com/nextcloud/docker/issues/1574 
- https://github.com/docker-library/wordpress/issues/630 

Somebody seems to have pinned down the issue and described the solution: https://github.com/tanmng/docker-chevereto/issues/36#issuecomment-1143035131

Let me know what you think about it

**Comment by 201206030** [comment]
> 

Thanks, I see, it's because of Apache web server.

**Comment by williamdes** [comment]
> > 
> 
> Thanks, I see. it's because of Apache web server.

The kernel version and the apache version seem to be the combination that leads to this error
I am closing this issue but feel free to post any helpful comment here for other users that will have this issue

**Comment by 201206030** [comment]
> > > 
> > 
> > 
> > Thanks, I see. it's because of Apache web server.
> 
> The kernel version and the apache version seem to be the combination that leads to this error I am closing this issue but feel free to post any helpful comment here for other users that will have this issue

OK!
