### ISSUE TITLE
Why this version of php-fpm build without nginx?

### ISSUE THREAD

**Issue by cffycls** [phpmyadmin/docker#374]
This repository contains only Docker integration of phpMyAdmin.

Please do not report bugs in phpMyAdmin itself here, use
<https://github.com/phpmyadmin/phpmyadmin/issues> instead.

**Comment by williamdes** [comment]
Hi
Because there is no nginx variant, see discussion in https://github.com/phpmyadmin/docker/issues/346

But basically the variant you mentioned has nothing to do with nginx ;)
Maybe you can elaborate so I can explain better?
