### ISSUE TITLE
Allow setting MAX_EXECUTION_TIME for Docker Containers

### ISSUE THREAD

**Issue by Okeanos** [phpmyadmin/docker#378]
### Is your feature request related to a problem? Please describe.

As briefly/incompletely described in phpmyadmin/phpmyadmin#6090 phpMyAdmin may encounter timeouts when processing large database files. The Docker image offers an environment variable to allow large database uploads via `UPLOAD_LIMIT`, however, no corresponding way to increase the maximum execution time for PHP scripts exists.

### Describe the solution you'd like

I would like to have a Docker environment variable `MAX_EXECUTION_TIME` that allows specifying arbitrary timeout values for the PHP `MAX_EXECUTION_TIME` setting.

### Describe alternatives you've considered

I considered manually overriding the PHP config in the container e.g. with a volume mount of a custom config as described in the [PHP Docker image](https://hub.docker.com/_/php) "Configuration" Section. However, this depends on a larger number of assumptions (such as the upstream PHP image, etc.) that I am not comfortable with, particularly because it's a very simple setting that complements the existing `UPLOAD_LIMIT` one that already exists.

### Additional context

- phpMyAdmin version: Any docker image (< 5.2.0) released previously to me filing this issue would be affected.

**Comment by williamdes** [comment]
It seems like https://hub.docker.com/_/phpmyadmin is out of date from the source https://hub.docker.com/r/phpmyadmin/phpmyadmin 

I will try to find out why

But, we already have `MAX_EXECUTION_TIME` ENV variable as you can see on the README. 
Does it work for you?

**Comment by Okeanos** [comment]
Wow … okay. That's really neat. Thanks for pointing that out.

Assuming [this](https://docs.phpmyadmin.net/en/latest/setup.html#installing-using-docker) is the official documentation – the environment variables are not up to date here, either. I actually checked that together with the official Docker image you linked and came to the conclusion it's a missing feature.

**Comment by williamdes** [comment]
Should be fixed now for the official documentation: https://docs.phpmyadmin.net/en/qa_5_2/setup.html#installing-using-docker

**Comment by Okeanos** [comment]
Thanks for taking care of this so quickly ❤️

**Comment by williamdes** [comment]
The Docker Hub page is now up to date too !
https://hub.docker.com/_/phpmyadmin
