### ISSUE TITLE
Cannot change configuration options

### ISSUE THREAD

**Issue by roelvanduijnhoven** [phpmyadmin/docker#38]
I would like to change some other configuration values that are *not* settable via environment variables (`FirstLevelNavigationItems` in this case). However it seems there is no way to do this at the moment.

A good way to implement this would be via volume mapping. My proposal would be to:

1. Add a `include '/config.inc.php';`  as a last line to `config.inc.php` in this repo.

2. Make the `Dockerfile` create an empty PHP file to that location.

3. Document that one can volume map a PHP file to that location. Ie:

   ```Dockerfile
   phpmyadmin:
     volumes:
       - ./some/local/file.inc.php:/config.inc.php
   ```

Now any configuration option can be set or overwritten.

Any thoughts on this?

**Comment by nijel** [comment]
Sounds like a good idea.

**Comment by marcelboettcher** [comment]
nice, need this as well for the nasty timeout

**Comment by Illydth** [comment]
This would enable PMA DB / Configuration Storage as well.  This should be a mandatory thing and I just went through the process to get it working on my system.

I would recommend, however, that you DO NOT override config.inc.php.  Instead a user hook should be installed as the last line in the current config.inc.php:

include('config.userdef.inc.php');

In this way, users could override / set any PHPMYADMIN setting (including but not limited to PMA DB Settings) through a local file without being a problem if it doesn't exist.

run.sh could "touch /www/config.userdef.inc.php" somewhere in it's code assuming no one wants the warning message thrown if a user doesn't volume map it.

If anyone wants a pull request done, please let me know as i've got all the code already ready to go.

**Comment by marcelboettcher** [comment]
@Illydth sound great! I like that solution.

**Comment by Illydth** [comment]
I've created pull request #42 to address this and Issue #41 as well.  This should be a catchall for updating any phpmyadmin config settings.

**Comment by roelvanduijnhoven** [comment]
@Illydth This is exactly what I hoped for. Thanks for taking the time to implement this one.

**Comment by nijel** [comment]
It is now possible to override configuration in /config.user.inc.php, see https://docs.phpmyadmin.net/en/latest/setup.html#installing-using-docker
