### ISSUE TITLE
Suddenly error "Wrong permissions on configuration file, should not be world writable" appeared

### ISSUE THREAD

**Issue by sneakyx** [phpmyadmin/docker#383]
This morning I couldn't login into phpmyadmin. 
The known error 
"Wrong permissions on configuration file, should not be world writable" appeared without any changes made to the container. The file 

I could change the permissions to this file with 
`docker exec phpmyadmin chmod 0644 /etc/phpmyadmin/config.inc.php`
but it seems the inital setting (777) to this file set by this container is wrong and the container doesn't work out of the box.

I start the container with `docker run --name phpmyadmin -d -e PMA_HOST=ip_of_server -p 8001:80 phpmyadmin:5`

**Comment by williamdes** [comment]
Hi @sneakyx 
I am not sure you are up to date, can you check ?

Here is my full log:
```
$ docker pull phpmyadmin:5
5: Pulling from library/phpmyadmin
Digest: sha256:a2b5cef8fd7f3d24d23efc2ae52ddd45b8a090cdd968563ba371ab4e891f2fd6
Status: Image is up to date for phpmyadmin:5
docker.io/library/phpmyadmin:5
$ docker run --name phpmyadmin -d -e PMA_HOST=ip_of_server -p 8001:80 phpmyadmin:5
527efb23a6aed02816c6a77366216a1feb63b20bfc88983c40679cdd2a5f94d8
$ docker logs -f phpmyadmin
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
[Wed Sep 07 16:24:20.246672 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.54 (Debian) PHP/8.0.23 configured -- resuming normal operations
[Wed Sep 07 16:24:20.246697 2022] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
$ docker stop phpmyadmin
phpmyadmin
$ docker rm phpmyadmin
```

**Comment by sneakyx** [comment]
Thanks, it works with the newest version. As I said, the error appeared suddenly without update and pulling the image some days ago (before opening the ticket) didn't solve problem. I had to change the file rights.
But, it works now after pulling the newest version.
