### ISSUE TITLE
Make server host configurable on docker enviroment

### ISSUE THREAD

**Issue by cassiofb-dev** [phpmyadmin/docker#397]
Hi, I'm trying to use phpmyadmin on Docker but it only works if the host ip address is set to 0.0.0.0 (otherwise the browser says "this connection was reset"). I wanted that it would be easier to make this change on docker compose.

It's on line 133, the ip address is hard coded to localhost.

![image](https://user-images.githubusercontent.com/61878987/217824272-da367e7e-f955-4ddc-8c51-066b7a2fc321.png)

My docker compose for this image:

![image](https://user-images.githubusercontent.com/61878987/217824678-edd69695-14d5-42c4-8b75-4fa7fd667a61.png)

**Comment by cassiofb-dev** [comment]
Btw, I know I can change this passing my custom config file on my host system to docker container but it's more like an enhancement issue. That would be awesome if I could change this settings with something like:

```Compose
  database-manager:
    container_name: database-manager
    image: phpmyadmin:latest
    restart: always
    environment:
      PHPMYADMIN_HOST: 0.0.0.0
      PHPMYADMIN_PORT: 8080
    ports:
      - 8080:8080
    depends_on:
      - main-database
      - secondary-database
```

**Comment by cassiofb-dev** [comment]
I'm closing this issue as I don't even need to change the host (PMA_ARBITRARY solved my problem😅).

**Comment by williamdes** [comment]
> I'm closing this issue as I don't even need to change the host (PMA_ARBITRARY solved my problems).

Indeed PMA_ARBITRARY is there to allow you to input any server address :)
