### ISSUE TITLE
PMA_ABSOLUTE_URI not working anymore

### ISSUE THREAD

**Issue by port22** [phpmyadmin/docker#40]
I used to reverse-proxy phpmyadmin-docker via nginx-docker-proxy and have it in a sub-URL like https://mydomain.com/phpmyadmin/

Now that PMA_ABSOLUTE_URI has obviously been obsoleted, what now?

**Comment by cracker0dks** [comment]
same problem here. tany solution yet ?

**Comment by port22** [comment]
no ... but :4.6.2-3  is working

**Comment by cracker0dks** [comment]
mmm I got the same problem with 4.6.2-3: http://93.104.214.117/phpmyadmin 

ngnix:
```
location /phpmyadmin {
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_pass http://myadmin;
    }
```

I also checked the config.inc.php inside the container and found no $cfg['PmaAbsoluteUri']

**Comment by port22** [comment]
mhmm, I'll just post my config, maybe it helps you:

```docker run -e PMA_ABSOLUTE_URI="https://mydomain.com/phpmyadmin/" phpmyadmin/phpmyadmin:4.6.2-3```

```location /phpmyadmin/ {
                proxy_pass http://phpmyadmin/;
		proxy_redirect off;
		proxy_set_header Host $host;
        }
```
actually I'm not sure if proxy_redirect could be omitted, but seems the only difference.

I am using the default config from jwilder/nginx-proxy. Not sure if 
``` proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;```
is default there ... perhaps test switching that

**Comment by cracker0dks** [comment]
WOW nice! I think I missed a / at some point thank you :)

**Comment by cracker0dks** [comment]
ok now I tested and it with the working settings for :4.6.2-3and it worked with the :latest build as well! can you give it a try ?

**Comment by port22** [comment]
tested, well, not really working. The Login page has <form action="index.php"> so it will trigger /index.php instead of /phpmyadmin/index.php  
If I manually change the url after login, I'm in.

tested on chrome and firefox ingognito, no cache prob.

**Comment by cracker0dks** [comment]
yeah you are right. If you are logged in this is no prob. Login and logout are broken

**Comment by port22** [comment]
yarp. PMA_ABSOLUTE_URI must be integrated again.

**Comment by cracker0dks** [comment]
according to this: https://github.com/phpmyadmin/docker/commit/812590e038631e4b32c6af7f289e045e4db1b1b3
its no longer needed -.-

**Comment by nijel** [comment]
It was removed from Docker as it's no longer supported upstream, ``$cfg['PmaAbsoluteUri']`` has been removed. If you want it back, please open issue at https://github.com/phpmyadmin/phpmyadmin/issues

**Comment by cracker0dks** [comment]
ok thank you. I opend one https://github.com/phpmyadmin/phpmyadmin/issues/12374 :)

**Comment by cracker0dks** [comment]
thanks, but login/logout not working for me with this fix. I run it like this:

`docker run [...] -e PMA_ABSOLUTE_URI="https://mydomain.com/phpmyadmin/" -d --link mariadb:db phpmyadmin/phpmyadmin:latest`

If I login/logout it redirects me to "https://mydomain.com" without "/phpmyadmin" 
If I add it to the url by hand after redirect it works till logout

working without problems:
 `... phpmyadmin/phpmyadmin:4.6.2-3`

am I wrong?

**Comment by nijel** [comment]
As I've mentioned within the commit message:

> Please note that the setting will take no effect till phpMyAdmin 4.6.5.

**Comment by cracker0dks** [comment]
oh ok. thought it is closed and didnt read any commit msg :) :+1:

**Comment by jortkoopmans** [comment]
Got bitten by this one today as well. What nginx config worked for you in the end (with the broken login/logout)?

I couldnt get anywhere without rewriting, not sure if its best:

```
location ~ \/pma {
    rewrite ^/pma(/.*)$ $1 break;
    proxy_set_header X-Real-IP  $remote_addr;
    proxy_set_header HOST $host;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_pass      http://phpmyadmin1;
```
with PMA_ABSOLUTE_URI set to "http://example.net/pma/
Login and logout are broken....
Running latest container which should be v4.6.4

**Comment by nijel** [comment]
This will be fixed once 4.6.5 is out, in 4.6.4, the PMA_ABSOLUTE_URI has not effect.

**Comment by cracker0dks** [comment]
the broken login/logout woriking with the config from above: https://github.com/phpmyadmin/docker/issues/40#issuecomment-231215330

**Comment by sul4bh** [comment]
To conform, 4.6.5 is out and this is fixed yes?

**Comment by cracker0dks** [comment]
yep! i just installed it and this is fixed (again)! 👍

**Comment by jortkoopmans** [comment]
Confirmed, thanks for fixing this!

**Comment by sul4bh** [comment]
Yes, it works. Thank you, thank you.
