### ISSUE TITLE
PMA DB/Configuration Storage Missing from Docker Container Capability

### ISSUE THREAD

**Issue by Illydth** [phpmyadmin/docker#41]
As a follow-on to:
https://github.com/phpmyadmin/docker/issues/38

The docker configuration of PHPMYADMIN does not allow turning on of the PMADB / Configuration Storage settings for PHPMYADMIN, leaving it somewhat less functional than it's non-dockerized installation.  (This is among other non-configurable options).

This is easy to turn on without breaking or corrupting the current installation:

1) Put a user hook at the end of the current config.inc.php file:
include('./config.userdef.inc.php');

2) Document the override for users to write their own config options based off of the standard config.sample.inc.php file distributed with the base phpmyadmin package.
-v /some/local/directory/config.userdef.inc.php:/www/config.userdef.inc.php

3) Update run.sh to "touch" the config.userdef.inc.php file upon boot in the same way it creates the config.secrets.inc.php file.  This will keep the warning message from "include" from firing.
if [ ! -f /www/config.userdef.inc.php ]; then
  touch /www/config.userdef.inc.php
fi

The benefit to this approach is it leaves the code written to handle external variables alone and allows the config.inc.php file to continue being maintained by the maintainer of the docker files while still allowing users to configure their phpmyadmin installation in the same way they're capable of maintaining the non-dockerized version.  config.inc.php becomes a "hands off" file that no one needs to touch, and users still get the ability to configure the full range of phpmyadmin settings for their local installations.

If anyone wants, I can put a pull request together for this.

**Comment by nijel** [comment]
This sounds good.

**Comment by Illydth** [comment]
Pull Request #42 created to address this.  If you have issues, please let me know and I can update the pull request/code.

**Comment by nijel** [comment]
PR has been merged, though the path to the file has been changed to /config.user.inc.php, see https://docs.phpmyadmin.net/en/latest/setup.html#installing-using-docker
