### ISSUE TITLE
413 Request Entity Too Large 

### ISSUE THREAD

**Issue by Artanisky** [phpmyadmin/docker#413]
Hello, when trying to import data into a database (1 GB), it gives error 413 Request Entity Too Large 
![image](https://github.com/phpmyadmin/docker/assets/32029918/1251cd6e-fe07-4b05-9523-52d7475c4b03)
Although the limits have been raised to 4GB
![image](https://github.com/phpmyadmin/docker/assets/32029918/3c1d6c89-0769-47a5-8419-f77fa8933d7c)

DockerFile
![image](https://github.com/phpmyadmin/docker/assets/32029918/a2f30267-ef26-4719-b1a2-bf8e11964505)

config.user.inc.php
![image](https://github.com/phpmyadmin/docker/assets/32029918/04844ea1-d385-4980-9459-1b034b26a512)

How can this be fixed? Previously, when the db weighed less, everything worked (up to 1 GB)

**Comment by williamdes** [comment]
Reading your configuration, you should use `2G` as a value

**Comment by williamdes** [comment]
See: https://github.com/phpmyadmin/docker#environment-variables-summary

You should use `UPLOAD_LIMIT=2G`

**Comment by andreas-aeschlimann** [comment]
I tried to upload a 3GB file and my limit is set to 8G, the same error message appeared.

**Comment by nguyenhai97** [comment]
> I tried to upload a 3GB file and my limit is set to 8G, the same error message appeared.

Try to downgrade image to `phpmyadmin:5.1.3`, It work for me on Ubuntu 20.04.6 LTS

**Comment by patrickwasp** [comment]
@williamdes this is still an issue with the latest version of phpmyadmin. Setting an `UPLOAD_LIMIT` to `4G` for example will not let you upload a 2GB file if you're using `phpmyadmin:5.2.1` but the same configuration will work if using `phpmyadmin:5.1.3`.
