### ISSUE TITLE
use cp command to copy files to image

### ISSUE THREAD

**Issue by bckelley** [phpmyadmin/docker#427]
This repository contains only Docker integration of phpMyAdmin.

```Dockerfile
FROM phpmyadmin

WORKDIR /var/www/html

COPY ./themes/ /var/www/html/themes

ENTRYPOINT [ "/docker-entrypoint.sh" ]
CMD ["apache2-foreground"]
```

```bash
 => ERROR [3/3] COPY ./themes/ /var/www/html/themes                       0.0s
------
 > [3/3] COPY ./themes/ /var/www/html/themes:
------
Dockerfile:5
--------------------
   3 |     WORKDIR /var/www/html
   4 |
   5 | >>> COPY ./themes/ /var/www/html/themes
   6 |
   7 |     ENTRYPOINT [ "/docker-entrypoint.sh" ]
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref b57c8b91-47dc-4a34-9fe0-b50509a3883c::p1oqhlnsohkhj5a7td1ech7ta: "/themes": not found
```

Please do not report bugs in phpMyAdmin itself here, use
<https://github.com/phpmyadmin/phpmyadmin/issues> instead.

**Comment by williamdes** [comment]
Can you run `ls - lR` and give us the command you run to build the image?

**Comment by williamdes** [comment]
> everytime I build the image it writes over the themes already installed deleting pmahomme which breaks the interface. I have tried both COPY and ADD with the same result.

Okay, that's easier to debug
The copy the theme folder and not the root
```Dockerfile
COPY ./themes/boodark /var/www/html/themes/boodark
```

**Comment by williamdes** [comment]
> ls -lR 

I am looking to see your directory structure and see what the Docker daemon receives

**Comment by bckelley** [comment]
> what exactly am I looking for in `ls -lR` ?
> 
> Command to build : `docker build -t bckelley/phpmyadmin -f pma/Dockerfile .`

@williamdes it actually a combo of the file flag and me being in the wrong directory, oops. I did into another issue but I'm positive it's a docker issue.

**Comment by williamdes** [comment]
I am glad this helped you
Let us know if you need further help
