### ISSUE TITLE
ZIP bomb file detected in phpmyadmin docker

### ISSUE THREAD

**Issue by cgarcianaat** [phpmyadmin/docker#430]
This repository contains only Docker integration of phpMyAdmin.

Please do not report bugs in phpMyAdmin itself here, use
<https://github.com/phpmyadmin/phpmyadmin/issues> instead.

Running a scan to the phpmyadmin container detects a possible Zip bomb.
In the File
/usr/share/apache2/error/c
ontact.html.var

the message in the antivirus is:

"/usr/share/apache2/error/c
ontact.html.var/Content/Content/Content/Content/Content/Content/Content/Content/Content/Content/Content/Content/Content/Content/Content/Content as it is a Zip Bomb"

**Comment by williamdes** [comment]
Hi,

The file you reported is most probably located in your own data and not the data we ship with this container.
Could you please double check ?
