### ISSUE TITLE
mysqli::real_connect(): (HY000/2002): No such file or directory

### ISSUE THREAD

**Issue by pp2amd6** [phpmyadmin/docker#431]
I'm install phpmyadmin with docker but when I try to login i get error `mysqli::real_connect(): (HY000/2002): No such file or directory`

![image](https://github.com/phpmyadmin/docker/assets/4976837/4c18bf43-ab25-4eff-aca5-7779824a59d7)

I use `docker-compose.yml` config from [phpmyadmin DockerHUB page](https://hub.docker.com/_/phpmyadmin)

OS: Win 10
Docker: Docker Desktop 4.26.1 (131620)

**Comment by williamdes** [comment]
Hi,
Can you please share the full docker composer file here?

**Comment by williamdes** [comment]
From the screenshot I see you are doing something impossible, trying to connect to localhost.
Localhost is the phpMyAdmin container, not your computer.

You can fix this by using docker network mode host : `network_mode: host`

This is very similar to https://github.com/phpmyadmin/docker/issues/429

**Comment by pp2amd6** [comment]
@williamdes sorry my fault I forgot declare network. Now I set network and all works fine

**Comment by williamdes** [comment]
Gald to know it works fine now 🎉
