### ISSUE TITLE
 Impossible de se connecter à la base de données Le serveur a répondu : php_network_getaddresses: getaddrinfo for MySQL failed: H�te inconnu.

### ISSUE THREAD

**Issue by nouralanour01** [phpmyadmin/docker#436]
This repository contains only Docker integration of phpMyAdmin.

Please do not report bugs in phpMyAdmin itself here, use
<https://github.com/phpmyadmin/phpmyadmin/issues> instead.

**Comment by williamdes** [comment]
Bonjour,

Tout est dit dans le titre. Le nom utilisé n'existe pas.
Quel est votre `docker-compose.yml` ?
