### ISSUE TITLE
Container recreation kills session even with persisted sessions

### ISSUE THREAD

**Issue by JKHSDTV** [phpmyadmin/docker#443]
Despite a long session timeout (seven days), as well as persisting the session folder (`/sessions`), recreating the container somehow interrupts ones session. The old session file is still picked up and reused, but on every recreate, one has to log in again, as if the session vanished.

I can see the session file be created, accessed, written to and reused, so I would think all permissions are correct. I'm not sure how the container even notices that it's been restarted/recreated - PHP on its own is stateless, after all, and like I said, sessions are persisted.

**Comment by williamdes** [comment]
Hello
Thank you for reporting this issue. Maybe you should mount a volume to persist the blowfish secret in `/etc/phpmyadmin/config.secret.inc.php`
See 
https://github.com/phpmyadmin/docker/blob/f79c7073ab4f3abf9267735a3f69572ed8ae7628/docker-entrypoint.sh#L5-L8

**Comment by JKHSDTV** [comment]
Thanks, that worked, no more disruptions of working users from container restarts 👍

**Comment by williamdes** [comment]
> Thanks, that worked, no more disruptions of working users from container restarts 👍

Awesome, I think the README should be updated a bit.
