### ISSUE TITLE
Export always download index.htm

### ISSUE THREAD

**Issue by ciltocruz** [phpmyadmin/docker#446]
I have installed phpmyadmin with docker and when I click on export a database, it always downloads an index.htm file with the source code of the phpmyadmin home page
Is there any way to fix this?

**Comment by williamdes** [comment]
> I have installed phpmyadmin with docker and when I click on export a database, it always downloads an index.htm file with the source code of the phpmyadmin home page Is there any way to fix this?

How did you do the setup ?
This does not look like a Docker setup issue, or some wrong config between nginx and fpm

**Comment by ciltocruz** [comment]
I've been analyzing part of the html that is downloaded and I found this:

```
<html>
<body>
<!--StartFragment-->
<body>
--
  | <h1>phpMyAdmin - Error</h1>
  | <p>index.php: Missing parameter: what<a href="./doc/html/faq.html#faqmissingparameters" target="documentation"><img src="themes/dot.gif" title="Documentation" alt="Documentation" class="icon ic_b_help"></a><br>index.php: Missing parameter: export_type<a href="./doc/html/faq.html#faqmissingparameters" target="documentation"><img src="themes/dot.gif" title="Documentation" alt="Documentation" class="icon ic_b_help"></a><br></p>
  | </body>

<!--EndFragment-->
</body>
</html>
```

**Comment by ciltocruz** [comment]
Solved. My browser have an extension that blocks this download.

**Comment by williamdes** [comment]
Great, please open an issue on https://github.com/phpmyadmin/phpmyadmin if you have a reliable way to trigger the error `export_type` missing
