### ISSUE TITLE
Unable to nagivate

### ISSUE THREAD

**Issue by bkuhl** [phpmyadmin/docker#47]
I'm operating this docker container and am running into all kinds of problems.  Among many other issues, none of these filtering options actually filter the current "Browse" selection.  The tab will reload and that's it.

<img width="842" alt="screen shot 2016-08-14 at 8 59 19 am" src="https://cloud.githubusercontent.com/assets/524933/17649233/79c3b03e-61fd-11e6-9638-49872ab7242f.png">

**Comment by nijel** [comment]
What version do you use?

**Comment by bkuhl** [comment]
`phpmyadmin/phpmyadmin:4.6.3-1`

The URL is http://my-site.org:8000 so hopefully the port isn't messing up the URLs or anything.  I also can't use the "Edit" functionality in this screenshot.

**Comment by nijel** [comment]
It most likely is - it is another instance of #40.
