### ISSUE TITLE
PMA_ARBITRARY seems to be ignored in the latest image build (but its ok with the phpmyadmin/phpmyadmin:4.6.4-1 image)

### ISSUE THREAD

**Issue by ChieftainY2k** [phpmyadmin/docker#49]
PMA_ARBITRARY seems to be ignored in the latest image build (but its ok with the phpmyadmin/phpmyadmin:4.6.4-1 image)

Steps to reproduce:
1) Create docker-compose.yml with:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1

2) Goto phpmyadmin local app page, the "Server:" field is missing from the "Log in" form.

**Comment by nijel** [comment]
Probably environment is cleaned up when starting PHP FPM...
