### ISSUE TITLE
Missing Official Repository in DockerHub

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/docker#56]
The docker image marked as public at:
    https://hub.docker.com/r/phpmyadmin/phpmyadmin/
There is a process that will mark the image as official, more information:
    https://docs.docker.com/docker-hub/official_repos/
example of official repositories:
    https://hub.docker.com/_/wordpress/
    https://hub.docker.com/_/drupal/
it appears that official repos has some security benefits (apart from distinguish from other public repos) such as content trust (see issue: not signed docker image) enabled by docker itself.

fix:
    do the needed changes (there is a guideline), and apply for official repositories at DockerHub.

Reported by Emanuel Bronshtein.

**Comment by emanuelb** [comment]
Semi related, there is new program called Docker Store:
https://success.docker.com/Store
which has guidelines under "Tips for becoming a publisher:"
https://blog.docker.com/2016/06/docker-store/
currently PHPMyAdmin docker listed under community:
https://store.docker.com/community/images/phpmyadmin/phpmyadmin

**Comment by J0WI** [comment]
I think #51 is one of the major changes that need to be done for this.
I stumbled over a few big changes while playing around with multiple base images:

- [ ] the `etc/php.ini` is very confusing. All comments and default values should be removed. The custom values can be copied to `/usr/local/etc/php/conf.d/php-phpmyadmin.ini`.
- [ ] default values like the upload limit should not be changed (see discussion in https://github.com/docker-library/wordpress/issues/10).
- [ ] same for `php-fpm.conf`(remove it entirely?)
- [ ] user/group `nobody` is problematic, what's wrong with `www`/`www-data`?

Afterwards:
- [ ] test should be moved [here](https://github.com/docker-library/official-images/tree/master/test/tests)
- [ ] docs should be moved [here](https://github.com/docker-library/docs)
- [ ] request inclusion into the docker-library

Let me know what you think about this!

**Comment by nijel** [comment]
My feedback on this is: patches welcome. We really do not have anybody in the team interested in the docker and this is really best effort image I could create with my almost zero Docker knowledge...

**Comment by J0WI** [comment]
I've added #168 but #169 should be considered first.

**Comment by J0WI** [comment]
Do you care about backwards compatibility or will current users just be migrated to the new apache based image?

**Comment by J0WI** [comment]
After messing around with permissions I finally submitted #198.
So the last step is removing nginx and supervisord from this image and using upstream apache/nginx :tada:

**Comment by J0WI** [comment]
@nijel @ibennetch @williamdes
I think this is nearly done. But the inclusion request @docker-library can only be done with the support of a representative of @phpmyadmin:
https://github.com/docker-library/official-images/blob/master/NEW-IMAGE-CHECKLIST.md

**Comment by J0WI** [comment]
@ibennetch would be great if you could fix the automated builds on DockerHub. The current image variants are not built and there are already some pending security updates for PHP and its dependencies.

**Comment by nijel** [comment]
I've fixed wesite/CDN integration to fix build of daily snapshots. I've also pushed new tag to rebuild stable release.

**Comment by J0WI** [comment]
The tags should be updated as described here:
https://github.com/phpmyadmin/docker/pull/216/files#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by williamdes** [comment]
@J0WI 
 test should be moved here
 docs and examples should be moved here

Is this only files moving in our repo or a PR to docker is needed ?

**Comment by J0WI** [comment]
A PR to docker is needed for all further steps.

**Comment by J0WI** [comment]
> I think this is nearly done. But the inclusion request @docker-library can only be done with the support of a representative of @phpmyadmin:
> https://github.com/docker-library/official-images/blob/master/NEW-IMAGE-CHECKLIST.md

:ping_pong: @williamdes @ibennetch

**Comment by williamdes** [comment]
@J0WI can you open the documentation PR so I can open the library one ?

**Comment by J0WI** [comment]
Sure!
You just have to pipe the output of `generate-stackbrew-library.sh` in `official-images/library/phpmyadmin` for the library.

**Comment by williamdes** [comment]
Will close it when everything is online, sorry for the open-close noise

**Comment by williamdes** [comment]
"test should be moved here"
@J0WI is a PR needed ?

**Comment by J0WI** [comment]
I think this does not make much sense now. This depends on https://github.com/docker-library/official-images/pull/7288, otherwise they will just fail.

**Comment by J0WI** [comment]
This is finally done: https://hub.docker.com/_/phpmyadmin :tada:
