### ISSUE TITLE
missing restrictions of opcache functions usage via opcache.restrict_api/disable_functions in php.ini used by docker

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/docker#65]
https://secure.php.net/manual/en/opcache.configuration.php#ini.opcache.restrict-api

the value used as "start of path", more information:
    https://github.com/websharks/comet-cache/issues/733

fix:
    it will be better to disable it completely, didn't found way to do it, does it PHP bug/limitation? probably better to limit it using opcache.restrict_api (instead of using disable_functions for this)

Reported by Emanuel Bronshtein.

**Comment by emanuelb** [comment]
Can be disabled/fixed with the following hack by hanno (see first comment) in:
https://ma.ttias.be/mitigating-phps-long-standing-issue-opcache-leaking-sensitive-data/
By setting opcache.restrict_api to not-existent directory/directory where root can write to "/root"

**Comment by nijel** [comment]
There is just one FPM pool in the Docker container, so this vulnerability really does not affect us. However we don't use the API, so disabling it is probably good idea.
