### ISSUE TITLE
Multiple mysql servers

### ISSUE THREAD

**Issue by mc388** [phpmyadmin/docker#7]
I want to link more than one mysql container into phpmyadmin and this is not working.

It only works when I link only one container and named it `db`

**Comment by mc388** [comment]
Fixed it by overwriting the `config.inc.linked.php` file link [here](http://tecadmin.net/add-multiple-hosts-in-phpmyadmin/)

**Comment by nijel** [comment]
I think it makes sense to support this scenario directly as well...
