### ISSUE TITLE
User configuration not taken into account

### ISSUE THREAD

**Issue by ahfeel** [phpmyadmin/docker#73]
Using the latest image, I'm mounting a file under /config.user.inc.php as described in the documentation. The file is not loaded by the default config.inc.php.

After investigating, the file is mounted properly but the line `if (file_exists('/config.user.inc.php')) {`  return false, which means that the PHP code does not have access to this file. A simple scandir('/') returns false also.

I'm running Docker 1.11.1

**Comment by nijel** [comment]
That's caused by `open_basedir` restrictions. Probably the location of file should be changed to something else due to this....

**Comment by ahfeel** [comment]
Sounds pretty much like this was not tested... :-/

Do you want a pull request to fix this ?

**Comment by nijel** [comment]
It has been tested, but other changes broke that...

**Comment by nijel** [comment]
Fixed and I've also introduced CI check to make sure this feature works.
