### ISSUE TITLE
Unable to access phpMyAdmin

### ISSUE THREAD

**Issue by DigitalSolace** [phpmyadmin/docker#80]
Assistance greatly appreciated. Apologies if this in not the right forum to ask
I have a phpmyadmin container running on 8090:80 yet am unable access using http://server_ip:8090 .
Using phpmyadmin version 4.6.4  mysql 5.7  drupal 8.2.1 and php 7.0.1
docker ps -a shows the phpmyadmin container is up and running and linked to the mysql server
What am i missing?

**Comment by nijel** [comment]
Either use phpmyadmin_ip:80 or localhost:8090

**Comment by DigitalSolace** [comment]
Thanks Nijel, that's just the thing, neither of those work...
drupal server is running on: http://41.79.78.255:8080/ 
phpmyadmin not working on: http://41.79.78.255:8090/

**Comment by DigitalSolace** [comment]
Solved - this was a combination of the cloud service provider blocking ports and setting the PMA_HOST variable to the ip address of the MYSQL container found in docker inspect.
