### ISSUE TITLE
Documentation on docker-compose config.user.inc.php

### ISSUE THREAD

**Issue by jandor64** [phpmyadmin/docker#82]
I am having difficulty understanding how to add a config file here when using docker-compose, the instructions only seem to be for Docker CLI

Please advise if you can, thank you.

**Comment by trombini77** [comment]
jandor64, I use the phpmyadmin in Docker with docker compose using the following lines inside docker-compose.yml (I don´t know your skills with Docker but anyway create a docker-compose.yml in a location that you will run the docker-compose utility):

_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:80
    volumes:
     - /sessions_

In this example I also use the PMA_ABITRARY variable that enable to define the server host in the login phpmyadmin login page.
After this you can start only it using the following command (remember you need to be in the directory of docker-compose.yml file):
docker-compose up -d phpmyadmin

(up - start the container)
(-d - start as daemon)
(phpmyadmin - is the line "phpmyadmin:" in the docker-compose.yml).

I hope this help your understanding.

**Comment by jandor64** [comment]
@trombini77 Thank you for taking the time to answer my question. Unfortunately, it looks like I could have been clearer in my question. 

I do have PHPMyAdmin running, using a docker-compose.yml. What I was hoping to do was modify PHPMyAdmin's  settings, each time using a config.user.inc.php that is local to the project

The [documentation](https://github.com/phpmyadmin/docker#adding-custom-configuration) for this GitHub project only mentions how to do this from the terminal using the `run` command. 

I imagine the solution is to use a volume mapping, something like:
`volumes:
      - "./my_php_config.php:/etc/phpmyadmin/config.user.inc.php"`

However, I could not get this to work. Thank you for taking the time to look into this; hopefully, it helps others!

**Comment by nijel** [comment]
@jandor64 The path to the user configuration has been changed recently, so in case you're using older version of the Docker container phpMyAdmin will not use it.

**Comment by skorzhevsky** [comment]
@jandor64 works fine for me:

    volumes:
     - /sessions
     - ~/docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
     - /var/run/mysqld/mysqld.sock:/tmp/mysqld.sock

**Comment by nijel** [comment]
Thanks for confirming, I've added example to our documentation as well.

**Comment by skorzhevsky** [comment]
Just one thing, config.user.inc.php must start from "<?php", which was not obvious to me :)

**Comment by nijel** [comment]
Okay, I've added more information on this topic :-)

**Comment by jandor64** [comment]
Thank you @nijel and @skorzhevsky I'm sure this will be helpful to others!

**Comment by nijel** [comment]
If you still find something confusing, don't hesitate to open issue or submit patch ;-).
