### ISSUE TITLE
Missing MAINTAINER command in Dockerfile

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/docker#85]
more information about MAINTAINER command:
https://docs.docker.com/engine/reference/builder/#maintainer

fix:
add MAINTAINER command to Dockerfile, as done by other projects:
https://github.com/rethinkdb/rethinkdb-dockerfiles/blob/da98484fc73485fe7780546903d01dcbcd931673/jessie/2.0.4/Dockerfile#L3

**Comment by emanuelb** [comment]
The MAINTAINER command is Deprecated from 1.13.0, more information:
https://github.com/docker/docker/blob/master/docs/deprecated.md#maintainer-in-dockerfile
Thus, closing this issue (LABEL can be used to specify metadata)

**Comment by nijel** [comment]
I've added version label, but there really doesn't seem to be any standard for labels, it rather arbitrary key value storage... https://docs.docker.com/engine/reference/builder/#label
