### ISSUE TITLE
sql folder is missing which results in error

### ISSUE THREAD

**Issue by asolopovas** [phpmyadmin/docker#88]
Hi sql folder with the following files is missing: 
create_tables.sql
upgrade_column_info_4_3_0+.sql
upgrade_tables_mysql_4_1_2+

So when you try to execute it from phpmyadmin it throws an error 

https://files.phpmyadmin.net/phpMyAdmin/4.6.4/phpMyAdmin-4.6.4-all-languages.tar.gz

this file contains the folder but its not present when I open container. As I understand the reason behind that is 

25 line in dockfile    && rm -rf /www/js/jquery/src/ /www/js/openlayers/src/ /www/setup/ /www/sql/ /www/examples/ /www/test/ /www/po/ /www/templates/test/ /www/phpunit.xml.* /www/build.xml  /www/composer.json /www/RELEASE-DATE-$VERSION \

because the file the create_tables.sql is delete phpmyadmin cant generate pma tables as well as phpmysql  storage tables

**Comment by nijel** [comment]
Fixed by https://github.com/phpmyadmin/docker/pull/89, thanks!
