### ISSUE TITLE
Opcache optimizations to test

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/docker#98]
1. in case PHPMyAdmin compatible with:
opcache.use_cwd=0
https://github.com/nijel/docker/blob/master/etc/php.ini#L1852-L1856

2. change opcache.interned_strings_buffer according to size of all strings in PMA code:
https://superuser.com/questions/969386/php-5-6-what-does-opcache-interned-string-buffers-overflow-mean#1008158

3. opcache.load_comments=0 (as comments not used)

**Comment by nijel** [comment]
The use_cwd and load_comments are adjusted, tweaking with interned_strings_buffer doesn't make much sense for now as we have quite a lot of global strings and fitting them all would need way too much memory.
